/**************************************************************************/
/* Archivo:            ccjg0041.sql		                                  */
/* Objeto:             OTC_M_CONVENIO, OTC_M_FLUJO,OTC_D_FLUJO_SERV_ENRIQ,*/
/*					   OTC_M_TIPO_IDENTIFICADOR, OTC_M_EMPRESA		      */
/* Base de datos:      DB_OTC                                     		  */
/* Producto:           Recaudaciones                                      */
/* Disenado por:       Jonathan Guerrero                                  */
/* Fecha de escritura: 05/31/2022                                         */
/* Descripcion:        Script para agregar a la empresa al  menu OTC      */
/**************************************************************************/
/*                            MODIFICACIONES                              */
/*   FECHA     TAREA             AUTOR                  RAZON             */
/*05/31/2022  RECMPS-XXX 		Jonathan Guerrero    Emision inicial      */
/**************************************************************************/

-- OJO VERIFICAR EL SCRIPT DE TC (LOS CODIGOS DE CONVENIO Y COD IDENTIFICAODR)

  set serveroutput on;

DECLARE
  LV_MSG_INI VARCHAR2(100) := 'INICIO SCRIPT';
  LV_MSG_FIN VARCHAR2(100) := 'FINAL SCRIPT';
  LN_CODIGO_EMPRESA         NUMBER := 0;
  LN_CODIGO_GRUPO           NUMBER := 0;
  LN_CODIGO_CONVENIO        NUMBER := 0;
  LN_CODIGO_SERVICIO        NUMBER := 0;
  LN_CODIGO_CANAL           NUMBER := 0;
  LN_CODIGO_IDENTIFICADOR   NUMBER := 0;
  LN_CODIGO_PUNTOFINAL      NUMBER := 0;
  LN_CODIGO_FLUJO           NUMBER := 0;
  LN_CODIGO_FLUJOENRIQ      NUMBER := 0;
  LN_GRUPO_SERVICIO			NUMBER := 19;  --AUTOMOTORES PEATONES
  LV_COBIS_EMPRESA			VARCHAR2(5)  := '18786';
  LV_EMPRESA 				VARCHAR2(50) := 'ANT - Agencia Nacional de Tránsito';
  LV_RUC_EMPRESA			VARCHAR2(15) := '1768159999001';
  LV_FLUJO_SOA				VARCHAR2(4)  := 'RMS';
  LV_PUNTO_FINAL 			VARCHAR2(50) := 'Recaudaciones/Microservicio'; --EJEMPLO / CONSULTAR CON GIZLO
  LV_REPOSITORIO_PETICION	VARCHAR2(50) := '/opt/microservices/transformaciones';
  LV_EMPRESA_XSL			VARCHAR2(50) := 'RMS_ANT'; -- EJEMPLO / CONSULTAR CON GIZLO
BEGIN
  
  DBMS_OUTPUT.put_line(LV_MSG_INI);
    
  
  DBMS_OUTPUT.put_line('OBTENIENDO SECUENCIAS MAXIMAS TABLAS OTC');
  -- OBTENER MAXIMO CODIGO TABLAS OTC
  select MAX(EMP_ID)+1 into LN_CODIGO_EMPRESA from DB_OTC.OTC_M_EMPRESA;      
  select MAX(GRP_ID)+1 into LN_CODIGO_GRUPO from DB_OTC.OTC_M_GRUPO_SERVICIO; 
  select MAX(CNV_ID)+1 into LN_CODIGO_CONVENIO from DB_OTC.OTC_M_CONVENIO;
  select MAX(SRV_ID)+1 into LN_CODIGO_SERVICIO from DB_OTC.OTC_D_SERVICIO;
  select MAX(SC_ID)+1 into LN_CODIGO_CANAL from DB_OTC.OTC_D_SERVICIO_CANAL;
  select MAX(TID_ID)+1 into LN_CODIGO_IDENTIFICADOR from DB_OTC.OTC_M_TIPO_IDENTIFICADOR;
  select MAX(END_ID)+1 into LN_CODIGO_PUNTOFINAL from DB_OTC.OTC_M_PUNTO_FINAL;
  select MAX(FLU_ID)+1 into LN_CODIGO_FLUJO from DB_OTC.OTC_M_FLUJO;
  select MAX(FSE_ID)+1 into LN_CODIGO_FLUJOENRIQ from DB_OTC.OTC_D_FLUJO_SERV_ENRIQ;
    
    --*** REEMPLAZAR DATOS DE LA EMPRESA
    --1: EMPRESAS -- *****
    Insert into DB_OTC.OTC_M_EMPRESA (EMP_ID,EMP_IDENTIFICACION,EMP_NOMBRE,EMP_CODIGO,EMP_DESCRIPCION, EMP_BANCO) 
    values (LN_CODIGO_EMPRESA,LV_RUC_EMPRESA,LV_EMPRESA,LV_COBIS_EMPRESA,LV_EMPRESA, null);
    DBMS_OUTPUT.put_line('INSERTAR EMPRESA OK');
    
    --*** REEMPLAZAR DATOS DEL MEN�
    --2: GRUPO SERVICIO--
    Insert into DB_OTC.OTC_M_GRUPO_SERVICIO (GRP_ID,EMP_ID,CT_ID_TIPO_BANCA,CT_ID_TIPO_SERV,GRP_CONVENIO_VISIBLE,GRP_MATRICULABLE,GRP_MATRIC_MULTIPLE,GRP_VALIDABLE) 
    values (LN_CODIGO_GRUPO,LN_CODIGO_EMPRESA,'1',LN_GRUPO_SERVICIO,'1','1','0','0');
    DBMS_OUTPUT.put_line('INSERTAR GRUPO SERVICIO OK');
    
    --*** REEMPLAZAR CODIGO DE LA EMPRESA
    --3: CONVENIOS--
    Insert into DB_OTC.OTC_M_CONVENIO (CNV_ID,CNV_CODIGO,CNV_VISIBLE,CNV_ETIQUETA_CODIGO) 
    values (LN_CODIGO_CONVENIO,'CIT','1','Citaciones');
    DBMS_OUTPUT.put_line('INSERTAR CONVENIO OK CT');

    Insert into DB_OTC.OTC_M_CONVENIO (CNV_ID,CNV_CODIGO,CNV_VISIBLE,CNV_ETIQUETA_CODIGO) 
    values (LN_CODIGO_CONVENIO +1,'SOL','1','Solicitudes');
    DBMS_OUTPUT.put_line('INSERTAR CONVENIO OK TR');

    Insert into DB_OTC.OTC_M_CONVENIO (CNV_ID,CNV_CODIGO,CNV_VISIBLE,CNV_ETIQUETA_CODIGO) 
    values (LN_CODIGO_CONVENIO +2,'CDP','1','Convenios de Pago');
    DBMS_OUTPUT.put_line('INSERTAR CONVENIO OK CDP');
    
    --*** REEMPLAZAR NOMBRE DE LA EMPRESA
    --4: SERVICIOS--
    --Insert into DB_OTC.OTC_D_SERVICIO (SRV_ID,SRV_NOMBRE,GRP_ID,CNV_ID) 
    --values (LN_CODIGO_SERVICIO,LV_COBIS_EMPRESA,LN_CODIGO_GRUPO,LN_CODIGO_CONVENIO);
    --DBMS_OUTPUT.put_line('INSERTAR SERVICIO OK');
    Insert into DB_OTC.OTC_D_SERVICIO (SRV_ID,SRV_NOMBRE,GRP_ID,CNV_ID) 
    values (LN_CODIGO_SERVICIO,'ANT-TRAMITES',LN_CODIGO_GRUPO,LN_CODIGO_CONVENIO +1);
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO OK  SOL');

    Insert into DB_OTC.OTC_D_SERVICIO (SRV_ID,SRV_NOMBRE,GRP_ID,CNV_ID) 
    values (LN_CODIGO_SERVICIO + 1,'ANT-CITACIONES',LN_CODIGO_GRUPO,LN_CODIGO_CONVENIO);
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO OK  CIT');

    Insert into DB_OTC.OTC_D_SERVICIO (SRV_ID,SRV_NOMBRE,GRP_ID,CNV_ID) 
    values (LN_CODIGO_SERVICIO + 2,'ANT-CONVENIOS',LN_CODIGO_GRUPO,LN_CODIGO_CONVENIO +2);
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO OK  CDP');

    --5:SERVICIO CANAL--
    Insert into DB_OTC.OTC_D_SERVICIO_CANAL (SC_ID,SRV_ID,CAN_ID) 
    values (LN_CODIGO_CANAL,LN_CODIGO_SERVICIO,'1');
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO CANAL OK  SOL');

    Insert into DB_OTC.OTC_D_SERVICIO_CANAL (SC_ID,SRV_ID,CAN_ID) 
    values (LN_CODIGO_CANAL +1,LN_CODIGO_SERVICIO + 1,'1');
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO CANAL OK  CIT');

    Insert into DB_OTC.OTC_D_SERVICIO_CANAL (SC_ID,SRV_ID,CAN_ID) 
    values (LN_CODIGO_CANAL +2,LN_CODIGO_SERVICIO + 2,'1');
    DBMS_OUTPUT.put_line('INSERTAR SERVICIO CANAL OK  CDP');
    
    --*** REEMPLAZAR MENSAJE INFORMATIVO Y EXPRESION REGULAR PARA CONTROL DEL INSUMO A MATRICULAR
    --6:TIPO IDENTIFICADOR TRA?--
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR,'SOL',null,'','0','^([0-9]){12}$',null,LN_CODIGO_CONVENIO + 1,'Ingrese número de orden de pago','Orden de Pago','1');
    DBMS_OUTPUT.put_line('INSERTAR IDENTIFICADOR OK');
    
    --6:TIPO IDENTIFICADOR CIT--
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +1,'CED',null,	'0000000000',	'1',  '^([0-9]){10}$', null,LN_CODIGO_CONVENIO ,	    'Ingrese el número de c�dula',	'C�dula',	    '0');
    DBMS_OUTPUT.put_line('INSERTAR IDENTIFICADOR OK');
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +2,'RUC',null,'0000000000000',	'1',  '^([0-9]){13}$', null,LN_CODIGO_CONVENIO ,	    'Ingrese el número de RUC',	    'RUC',	        '0');
     DBMS_OUTPUT.put_line('INSERTAR IDENTIFICADOR OK 2');
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +3,'PAS',null,null,   	'1'	, '^([A-Z0-9]){1,20}$',	null,LN_CODIGO_CONVENIO,	'Ingrese el número de pasaporte','Pasaporte',	'0');
     DBMS_OUTPUT.put_line('INSERTAR IDENTIFICADOR OK 3');
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +4,'PLA',null,null,			'1'	, '^([A-Z0-9]){1,7}$',	null,LN_CODIGO_CONVENIO ,	'Ingrese el número de placa',	 'Placa',	 '0');
    DBMS_OUTPUT.put_line('INSERTAR IDENTIFICADOR OK 4');

    --6:TIPO IDENTIFICADOR CDP--
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +5,'CED',null,	'0000000000',	'1',  '^([0-9]){10}$', null,LN_CODIGO_CONVENIO + 2,	    'Ingrese el numero de c�dula',	'C�dula','0');
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +6,'RUC',null,'0000000000000',	'1',  '^([0-9]){13}$', null,LN_CODIGO_CONVENIO + 2,	    'Ingrese el numero de RUC',	    'RUC','0');
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +7,'PAS',null,null,   	'1'	, '^([A-Z0-9]){1,20}$',	null,LN_CODIGO_CONVENIO + 2,	'Ingrese el numero de pasaporte','Pasaporte',	'0');
    
    --6 TIPO CIT CARNET D REFUGIADO
    Insert into DB_OTC.OTC_M_TIPO_IDENTIFICADOR (TID_ID,TID_CODIGO,TID_CONCAT_REGIONAL_AREA,TID_MASCARA,TID_MATRICULABLE,TID_REGEXP,TID_FLUJO_AYUDA,CNV_ID,TID_TEXTO_AYUDA,TID_ETIQUETA_CODIGO,TID_PROGRAMABLE) 
    values (LN_CODIGO_IDENTIFICADOR +8,'CRE',null,null,   	'1'	, '^([A-Z0-9]){1,20}$',	null,LN_CODIGO_CONVENIO,	'Ingrese el numero de carnet de refugiado','Carnet de Refugiado',	'0');

    --*** REEMPLAZAR RUTA DEL PROXY LOCAL A CONSUMIR Y NOMBRES DE LAS TRANSFORMACIONES
    --*** EN CASO DE NECESITAR EL REVERSO AUMENTAR EN EL SCRIPT
    --7:ENDPOINT --
    Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL,LV_EMPRESA || ' CONSULTA',LV_PUNTO_FINAL,'Consultar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION,LV_EMPRESA_XSL || '_C_IN.xsl', LV_EMPRESA_XSL || '_C_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL CONSULTA OK');
    
	Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL+1,LV_EMPRESA || ' PAGO',LV_PUNTO_FINAL,'Pagar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION, LV_EMPRESA_XSL || '_P_IN.xsl', LV_EMPRESA_XSL || '_P_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL PAGAR OK');
    

	Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL+2,LV_EMPRESA || ' REVERSO',LV_PUNTO_FINAL,'Reversar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION, LV_EMPRESA_XSL || '_R_IN.xsl', LV_EMPRESA_XSL || '_R_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL REVERSAR OK');
    
    --** CONSIDERACIONES:
    --** 22 => CONSULTA
    --** 6  => PAGO
	  --** 23 => REVERSO
    --==================== SOLICITUD =========================================
    --8:FLUJO CONSULTA-- 
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO,LN_CODIGO_PUNTOFINAL,LN_CODIGO_CONVENIO+1,'22');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO CONSULTA OK  SL');
    -- 9:FLUJO CONSULTA --
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ,'1',LN_CODIGO_FLUJO);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ CONSULTA OK  SL');

    --8:FLUJO PAGO-- 
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+1,LN_CODIGO_PUNTOFINAL+1,LN_CODIGO_CONVENIO+1,'6');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO PAGO OK  SL');
    -- 9:FLUJO SERVICIO ENRIQ -- 
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+1,'1',LN_CODIGO_FLUJO+1);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ PAGO OK  SL');
	
	 --8:FLUJO REVERSO--       **************** CORREGIR CONTADOR LN_CODIGO_FLUJO  LN_CODIGO_FLUJOENRIQ
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+1,LN_CODIGO_PUNTOFINAL+1,LN_CODIGO_CONVENIO+1,'23');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO REVERSO OK  SL');
    -- 9:FLUJO SERVICIO ENRIQ -- 
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+1,'1',LN_CODIGO_FLUJO+1);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ REVERSO OK  SL');

    --==================== CITACIONES =========================================
    --8.1:FLUJO CONSULTA
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+2,LN_CODIGO_PUNTOFINAL,LN_CODIGO_CONVENIO,'22');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO CONSULTA OK  CIT');
    -- 9.1:FLUJO SERVICIO ENRIQ --
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+2,'1',LN_CODIGO_FLUJO+2);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ CONSULTA OK  CIT');

    --8.1:FLUJO PAGO    
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+3,LN_CODIGO_PUNTOFINAL+1,LN_CODIGO_CONVENIO,'6');    
    DBMS_OUTPUT.put_line('INSERTAR FLUJO PAGO OK CT'); 
    -- 9.1:FLUJO SERVICIO ENRIQ --    
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+3,'1',LN_CODIGO_FLUJO+3);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ PAGO OK  CT');

     --==================== CONVENIOS =========================================
    --8.1:FLUJO CONSULTA
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+4,LN_CODIGO_PUNTOFINAL,LN_CODIGO_CONVENIO +2,'22');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO CONSULTA OK  CDP');
    -- 9.1:FLUJO SERVICIO ENRIQ --
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+4,'1',LN_CODIGO_FLUJO+4);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ CONSULTA OK  CDP');

    --8.1:FLUJO PAGO    
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+5,LN_CODIGO_PUNTOFINAL+1,LN_CODIGO_CONVENIO +2,'6');    
    DBMS_OUTPUT.put_line('INSERTAR FLUJO PAGO OK CDP'); 
    -- 9.1:FLUJO SERVICIO ENRIQ --    
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+5,'1',LN_CODIGO_FLUJO+5);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ PAGO OK  CDP');

        ---CONVENIOS DE PAGOS POR TC
        --CITACIONES --CED
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',445,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',445,357);

        --CITACIONES --RUC
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',446,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',446,357);

        --CITACIONES --PASAPORTE
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',447,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',447,357);

        --CITACIONES --PLACA
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',448,357);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',448,357);

        --SOLICITUDES
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',444,358);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',444,358);

        --CONVENIO CED
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',449,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',449,359);

        --CONVENIO RUC
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',450,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',450,359);

        --CONVENIO PASAPORTE
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'3MESES',16.06,3,'TC','Diferido con intereses - 3 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'4MESES',16.06,4,'TC','Diferido con intereses - 4 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'5MESES',16.06,5,'TC','Diferido con intereses - 5 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'6MESES',16.06,6,'TC','Diferido con intereses - 6 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'9MESES',16.06,9,'TC','Diferido con intereses - 9 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'12MESES',16.06,12,'TC','Diferido con intereses - 12 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'15MESES',16.06,15,'TC','Diferido con intereses - 15 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'18MESES',16.06,18,'TC','Diferido con intereses - 18 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'24MESES',16.06,24,'TC','Diferido con intereses - 24 cuotas de #vc# USD',451,359);
        Insert into DB_OTC.OTC_D_FORMA_PAGO (FPA_ID,FPA_NOMBRE,FPA_INTERES,FPA_CUOTAS,FPA_MEDIO,FPA_ETIQUETA,TID_ID,CNV_ID) 
        values (SEQ_OTC_D_FORMA_PAGO.NEXTVAL,'36MESES',16.06,36,'TC','Diferido con intereses - 36 cuotas de #vc# USD',451,359);
    -- CONFIRMAR
    --COMMIT;
    
    DBMS_OUTPUT.put_line('******************* DATOS INSERTADOS **************************');
    DBMS_OUTPUT.put_line('CODIGO EMPRESA : '        ||LN_CODIGO_EMPRESA);
    DBMS_OUTPUT.put_line('CODIGO GRUPO SERVICIO : ' ||LN_CODIGO_GRUPO);
    DBMS_OUTPUT.put_line('CODIGO CONVENIO CT: '     ||LN_CODIGO_CONVENIO);
    DBMS_OUTPUT.put_line('CODIGO CONVENIO TR: '     || TO_CHAR(LN_CODIGO_CONVENIO +1));
    DBMS_OUTPUT.put_line('CODIGO CONVENIO CDP: '    || TO_CHAR(LN_CODIGO_CONVENIO +2));
    DBMS_OUTPUT.put_line('CODIGO SERVICIO CT: '     ||LN_CODIGO_SERVICIO);
    DBMS_OUTPUT.put_line('CODIGO SERVICIO TR: '     || TO_CHAR(LN_CODIGO_SERVICIO +1));
    DBMS_OUTPUT.put_line('CODIGO SERVICIO TR: '     || TO_CHAR(LN_CODIGO_SERVICIO +2));
    DBMS_OUTPUT.put_line('SERVICIO CANAL TR: '      ||LN_CODIGO_CANAL);
	  DBMS_OUTPUT.put_line('SERVICIO CANAL CT: '      ||TO_CHAR(LN_CODIGO_CANAL +1));
    DBMS_OUTPUT.put_line('SERVICIO CANAL CDP: '     ||TO_CHAR(LN_CODIGO_CANAL +2));  

    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||LN_CODIGO_IDENTIFICADOR);  
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +1));
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +2));
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +3));
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +4));
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +5));
    DBMS_OUTPUT.put_line('TIPO_IDENTIFICADOR: '     ||TO_CHAR(LN_CODIGO_IDENTIFICADOR +6));

    DBMS_OUTPUT.put_line('CODIGO PUNTO FINAL CONSULTAR : '  ||LN_CODIGO_PUNTOFINAL);
    DBMS_OUTPUT.put_line('CODIGO PUNTO FINAL PAGAR : '      ||TO_CHAR(LN_CODIGO_PUNTOFINAL+1));
    DBMS_OUTPUT.put_line('******************* COD SL **************************');
    DBMS_OUTPUT.put_line('CODIGO FLUJO CONSULTA SL: '       ||LN_CODIGO_FLUJO);
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ CONSULTA SL: ' ||LN_CODIGO_FLUJOENRIQ);
    DBMS_OUTPUT.put_line('CODIGO FLUJO PAGO SL: '           ||TO_CHAR(LN_CODIGO_FLUJO+1));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ PAGO SL: '     ||TO_CHAR(LN_CODIGO_FLUJOENRIQ+1));
    DBMS_OUTPUT.put_line('******************* COD CT **************************');
    DBMS_OUTPUT.put_line('CODIGO FLUJO CONSULTA TR: '      ||TO_CHAR(LN_CODIGO_FLUJO + 2));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ CONSULTA TR: ' ||TO_CHAR(LN_CODIGO_FLUJOENRIQ + 2));
    DBMS_OUTPUT.put_line('CODIGO FLUJO PAGO TR: '           ||TO_CHAR(LN_CODIGO_FLUJO+3));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ PAGO TR: '     ||TO_CHAR(LN_CODIGO_FLUJOENRIQ+3));
    DBMS_OUTPUT.put_line('******************* COD CDP **************************');
    DBMS_OUTPUT.put_line('CODIGO FLUJO CONSULTA CDP: '      ||TO_CHAR(LN_CODIGO_FLUJO + 4));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ CONSULTA CDP: ' ||TO_CHAR(LN_CODIGO_FLUJOENRIQ + 4));
    DBMS_OUTPUT.put_line('CODIGO FLUJO PAGO CDP: '           ||TO_CHAR(LN_CODIGO_FLUJO+5));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ PAGO CDP: '     ||TO_CHAR(LN_CODIGO_FLUJOENRIQ+5));

    DBMS_OUTPUT.put_line(LV_MSG_FIN);
 
  
  EXCEPTION
  WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.put_line(DBMS_UTILITY.format_error_stack);
  
END;
/

	select EMP_CODIGO from DB_OTC.OTC_M_EMPRESA  where EMP_CODIGO = '18786';
	--select CNV_CODIGO from DB_OTC.OTC_M_CONVENIO  where CNV_CODIGO = '18786';
	select SRV_NOMBRE from DB_OTC.OTC_D_SERVICIO where SRV_NOMBRE = 'ATN-TRAMITES';
	select END_NOMBRE from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'ANT - Agencia Nacional de Tránsito CONSULTA';
	select END_NOMBRE from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'ANT - Agencia Nacional de Tránsito PAGO';
	
	/*
    delete  from DB_OTC.OTC_D_FLUJO_SERV_ENRIQ where FSE_ID in (497,498,499,500,501,502);    
    delete from DB_OTC.OTC_M_FLUJO where FLU_ID in (1082,1083,1084,1085,1086,1087);
    delete from DB_OTC.OTC_M_PUNTO_FINAL where END_ID in (211,212);  
    delete from DB_OTC.OTC_M_TIPO_IDENTIFICADOR where  TID_ID in(444,445,446,447,448,449,450,451);
    delete from DB_OTC.OTC_D_SERVICIO_CANAL where SC_ID in (161,162,163);
    delete from DB_OTC.OTC_D_SERVICIO where SRV_ID in(938,939,940);    
    delete from DB_OTC.OTC_M_CONVENIO where CNV_ID in (357,358,359); 
    delete from DB_OTC.OTC_M_GRUPO_SERVICIO where GRP_ID = 732;
    delete from DB_OTC.OTC_M_EMPRESA where EMP_ID = 465;    
    */
/*
    INICIO SCRIPT

******************* DATOS INSERTADOS **************************
CODIGO EMPRESA : 465
CODIGO GRUPO SERVICIO : 732
CODIGO CONVENIO CT: 357
CODIGO CONVENIO TR: 358
CODIGO CONVENIO CDP: 359
CODIGO SERVICIO CT: 938
CODIGO SERVICIO TR: 939
CODIGO SERVICIO TR: 940
SERVICIO CANAL TR: 161
SERVICIO CANAL CT: 162
SERVICIO CANAL CDP: 163

TIPO_IDENTIFICADOR: 444
TIPO_IDENTIFICADOR: 445
TIPO_IDENTIFICADOR: 446
TIPO_IDENTIFICADOR: 447
TIPO_IDENTIFICADOR: 448
TIPO_IDENTIFICADOR: 449
TIPO_IDENTIFICADOR: 450
TIPO_IDENTIFICADOR: 451
CODIGO PUNTO FINAL CONSULTAR : 211
CODIGO PUNTO FINAL PAGAR : 212
******************* COD TR **************************
CODIGO FLUJO CONSULTA TR: 1082
CODIGO FLUJO ENRIQ CONSULTA TR: 497
CODIGO FLUJO PAGO TR: 1083
CODIGO FLUJO ENRIQ PAGO TR: 498
******************* COD CT **************************
CODIGO FLUJO CONSULTA TR: 1084
CODIGO FLUJO ENRIQ CONSULTA TR: 499
CODIGO FLUJO PAGO TR: 1085
CODIGO FLUJO ENRIQ PAGO TR: 500
******************* COD CDP **************************
CODIGO FLUJO CONSULTA CDP: 1086
CODIGO FLUJO ENRIQ CONSULTA CDP: 501
CODIGO FLUJO PAGO CDP: 1087
CODIGO FLUJO ENRIQ PAGO CDP: 502
FINAL SCRIPT

Procedimiento PL/SQL terminado correctamente.
OBTENIENDO SECUENCIAS MAXIMAS TABLAS OTC
INSERTAR EMPRESA OK
INSERTAR GRUPO SERVICIO OK
INSERTAR CONVENIO OK CT
INSERTAR CONVENIO OK TR
INSERTAR CONVENIO OK CDP
INSERTAR SERVICIO OK  TR
INSERTAR SERVICIO OK  CT
INSERTAR SERVICIO OK  CDP
INSERTAR SERVICIO CANAL OK  TR
INSERTAR SERVICIO CANAL OK  CT
INSERTAR SERVICIO CANAL OK  CDP
INSERTAR IDENTIFICADOR OK
INSERTAR IDENTIFICADOR OK
INSERTAR IDENTIFICADOR OK 2
INSERTAR IDENTIFICADOR OK 3
INSERTAR IDENTIFICADOR OK 4
INSERTAR PUNTO FINAL CONSULTA OK
INSERTAR PUNTO FINAL PAGAR OK
INSERTAR FLUJO CONSULTA OK  TR
INSERTAR FLUJO ENRIQ CONSULTA OK  TR
INSERTAR FLUJO PAGO OK  TR
INSERTAR FLUJO ENRIQ PAGO OK  TR
INSERTAR FLUJO CONSULTA OK  CT
INSERTAR FLUJO ENRIQ CONSULTA OK  CT
INSERTAR FLUJO PAGO OK CT
INSERTAR FLUJO ENRIQ PAGO OK  CT
INSERTAR FLUJO CONSULTA OK  CDP
INSERTAR FLUJO ENRIQ CONSULTA OK  CDP
INSERTAR FLUJO PAGO OK CDP
INSERTAR FLUJO ENRIQ PAGO OK  CDP
*/


