//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTCSATServices.ClienteFramework {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bolivariano.com/WSFrameWork/", ConfigurationName="ClienteFramework.ServicioSeguridadSCLSoap")]
    public interface ServicioSeguridadSCLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/LoginAplicacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginAplicacion(int IdAplicacion, string UsrApl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/LoginAplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAplicacionAsync(int IdAplicacion, string UsrApl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/DesRegistraUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DesRegistraUser(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/DesRegistraUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DesRegistraUserAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/RegistraUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegistraUser(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/RegistraUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegistraUserAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/VerificaUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VerificaUser(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/VerificaUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VerificaUserAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/IsPermisoUserTransOpcion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsPermisoUserTransOpcion(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/IsPermisoUserTransOpcion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IsPermisoUserTransOpcionAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransacciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EjecutaTransacciones(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransacciones", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EjecutaTransaccionesAsync(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransaccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EjecutaTransaccion(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransaccion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EjecutaTransaccionAsync(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransaccionDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EjecutaTransaccionDS(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/EjecutaTransaccionDS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EjecutaTransaccionDSAsync(string XmlSeccion, string XmlEntrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsParamAplicacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsParamAplicacion(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsParamAplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsParamAplicacionAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/IsPermisoAplTransOpcion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsPermisoAplTransOpcion(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/IsPermisoAplTransOpcion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IsPermisoAplTransOpcionAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsSemillaPart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsSemillaPart(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsSemillaPart", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsSemillaPartAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ExecCmdUnix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecCmdUnix(string PI_xmlSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ExecCmdUnix", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExecCmdUnixAsync(string PI_xmlSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ExecCmdWindows", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecCmdWindows(string PI_xmlSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ExecCmdWindows", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExecCmdWindowsAsync(string PI_xmlSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEsp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultaLLaveEsp(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEsp", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultaLLaveEspAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEspFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultaLLaveEspFile(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEspFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultaLLaveEspFileAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEspFileRS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultaLLaveEspFileRS(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveEspFileRS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultaLLaveEspFileRSAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveKEY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultaLLaveKEY(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsultaLLaveKEY", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultaLLaveKEYAsync(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsLLavesServicio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsLLavesServicio(string PI_xmlParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bolivariano.com/WSFrameWork/ConsLLavesServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsLLavesServicioAsync(string PI_xmlParam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSeguridadSCLSoapChannel : OTCSATServices.ClienteFramework.ServicioSeguridadSCLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSeguridadSCLSoapClient : System.ServiceModel.ClientBase<OTCSATServices.ClienteFramework.ServicioSeguridadSCLSoap>, OTCSATServices.ClienteFramework.ServicioSeguridadSCLSoap {
        
        public ServicioSeguridadSCLSoapClient() {
        }
        
        public ServicioSeguridadSCLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSeguridadSCLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeguridadSCLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeguridadSCLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginAplicacion(int IdAplicacion, string UsrApl) {
            return base.Channel.LoginAplicacion(IdAplicacion, UsrApl);
        }
        
        public System.Threading.Tasks.Task<string> LoginAplicacionAsync(int IdAplicacion, string UsrApl) {
            return base.Channel.LoginAplicacionAsync(IdAplicacion, UsrApl);
        }
        
        public string DesRegistraUser(string PI_xmlParam) {
            return base.Channel.DesRegistraUser(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> DesRegistraUserAsync(string PI_xmlParam) {
            return base.Channel.DesRegistraUserAsync(PI_xmlParam);
        }
        
        public string RegistraUser(string PI_xmlParam) {
            return base.Channel.RegistraUser(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> RegistraUserAsync(string PI_xmlParam) {
            return base.Channel.RegistraUserAsync(PI_xmlParam);
        }
        
        public string VerificaUser(string PI_xmlParam) {
            return base.Channel.VerificaUser(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> VerificaUserAsync(string PI_xmlParam) {
            return base.Channel.VerificaUserAsync(PI_xmlParam);
        }
        
        public string IsPermisoUserTransOpcion(string PI_xmlParam) {
            return base.Channel.IsPermisoUserTransOpcion(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> IsPermisoUserTransOpcionAsync(string PI_xmlParam) {
            return base.Channel.IsPermisoUserTransOpcionAsync(PI_xmlParam);
        }
        
        public string EjecutaTransacciones(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransacciones(XmlSeccion, XmlEntrada);
        }
        
        public System.Threading.Tasks.Task<string> EjecutaTransaccionesAsync(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransaccionesAsync(XmlSeccion, XmlEntrada);
        }
        
        public string EjecutaTransaccion(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransaccion(XmlSeccion, XmlEntrada);
        }
        
        public System.Threading.Tasks.Task<string> EjecutaTransaccionAsync(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransaccionAsync(XmlSeccion, XmlEntrada);
        }
        
        public System.Data.DataSet EjecutaTransaccionDS(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransaccionDS(XmlSeccion, XmlEntrada);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EjecutaTransaccionDSAsync(string XmlSeccion, string XmlEntrada) {
            return base.Channel.EjecutaTransaccionDSAsync(XmlSeccion, XmlEntrada);
        }
        
        public string ConsParamAplicacion(string PI_xmlParam) {
            return base.Channel.ConsParamAplicacion(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsParamAplicacionAsync(string PI_xmlParam) {
            return base.Channel.ConsParamAplicacionAsync(PI_xmlParam);
        }
        
        public string IsPermisoAplTransOpcion(string PI_xmlParam) {
            return base.Channel.IsPermisoAplTransOpcion(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> IsPermisoAplTransOpcionAsync(string PI_xmlParam) {
            return base.Channel.IsPermisoAplTransOpcionAsync(PI_xmlParam);
        }
        
        public string ConsSemillaPart(string PI_xmlParam) {
            return base.Channel.ConsSemillaPart(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsSemillaPartAsync(string PI_xmlParam) {
            return base.Channel.ConsSemillaPartAsync(PI_xmlParam);
        }
        
        public string ExecCmdUnix(string PI_xmlSession) {
            return base.Channel.ExecCmdUnix(PI_xmlSession);
        }
        
        public System.Threading.Tasks.Task<string> ExecCmdUnixAsync(string PI_xmlSession) {
            return base.Channel.ExecCmdUnixAsync(PI_xmlSession);
        }
        
        public string ExecCmdWindows(string PI_xmlSession) {
            return base.Channel.ExecCmdWindows(PI_xmlSession);
        }
        
        public System.Threading.Tasks.Task<string> ExecCmdWindowsAsync(string PI_xmlSession) {
            return base.Channel.ExecCmdWindowsAsync(PI_xmlSession);
        }
        
        public string ConsultaLLaveEsp(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEsp(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaLLaveEspAsync(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEspAsync(PI_xmlParam);
        }
        
        public System.Data.DataSet ConsultaLLaveEspFile(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEspFile(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultaLLaveEspFileAsync(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEspFileAsync(PI_xmlParam);
        }
        
        public string ConsultaLLaveEspFileRS(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEspFileRS(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaLLaveEspFileRSAsync(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveEspFileRSAsync(PI_xmlParam);
        }
        
        public string ConsultaLLaveKEY(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveKEY(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaLLaveKEYAsync(string PI_xmlParam) {
            return base.Channel.ConsultaLLaveKEYAsync(PI_xmlParam);
        }
        
        public string ConsLLavesServicio(string PI_xmlParam) {
            return base.Channel.ConsLLavesServicio(PI_xmlParam);
        }
        
        public System.Threading.Tasks.Task<string> ConsLLavesServicioAsync(string PI_xmlParam) {
            return base.Channel.ConsLLavesServicioAsync(PI_xmlParam);
        }
    }
}
