kind: ConfigMap
apiVersion: v1
metadata:
  name: otc-collector-application-yml
  namespace: bb-dev-otc
data:
  application.yml: >
    otc-collector:
      sybase:
        datasource:
          username: operadorRec
          password: Ope+1234Rec
          hostPort: 172.16.23.22:2030
          jdbcUrl: jdbc:sybase:Tds:172.16.23.22:2030
          driverClassName: com.sybase.jdbc4.jdbc.SybDriver
          dbName: db_biz_pagos