cob_pagos..sp_helptext pa_pg_pval_rev_core, null, null, showsql
=============================================================
select * from cob_cuentas..cc_tran_servicio 
where 
ts_tsfecha = '02/24/2022' and 
ts_causa = '7749' and 
ts_campo_alt_dos = '005100028000030000000000000' and 
ts_stick_imp = '2022'
-- ts_corresponsal = 001 es igual al servicio 03


ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
41237756      0              3215                NOR      Feb 24 2022 12:00AM         (null)   ope998                                                           term24                                                           5      N             (null)      N          L         BOLIVSRV                       005100028000030 (null)        0             (null)      0861014083               1         0          (null)     (null)                      (null)      (null)        (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      (null)  (null)       1         (null)      (null)      (null)      (null)           (null)    (null)                      3                                                                7749     (null)      0.00                       (null)                      21.09                      (null)                      (null)        (null)     0.45                                                             (null)          (null)                                                                        (null)          (null)          (null)      (null)         (null)          (null)                   (null)      (null)       001             (null)         (null)      (null)            (null)      (null)                   (null)          (null)                     0.00                       (null)                     (null)   (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      IBK              2022         (null)      (null)               (null)                     (null)                     (null)                     123775                         GUADALUPE VIZUETE AMADA LUCIA                                                                                            (null)    Feb 24 2022 11:27AM         (null)         0           (null)           (null)        (null)          (null)   (null)            (null)                         005100028000030000000000000    0            

declare
@w_return  int
begin
 exec @w_return = dbo.pa_pg_pval_rev_core
@e_empresa	 = '7749',
@e_suministro	 = '005100028000030000000000000',
@e_canal	 = 'IBK',
@e_usuario   	 = 'ope998',
@e_identificacion= '2022',
@e_fecha	 = '02/24/2022',
@t_debug     	 = 'N',
@t_file      	 = null,
@e_servicio   	 = '03' 
print '%1!' , @w_return
end
--901422


=============================================================
select ts_referencia, * from cob_cuentas..cc_tran_servicio 
where 
ts_tsfecha = '04/29/2022' and
ts_corresponsal = '004'


ts_referencia   ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
--------------- ------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
0000077846      51379846      0              3216                NOR      Apr 29 2022 12:00AM         (null)   ope998                                                           term24                                                           5      N             (null)      N          L         BOLIVSRV                       0000077846      (null)        0             (null)      0005307799               1         0          (null)     (null)                      (null)      (null)        (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      (null)  (null)       1         (null)      (null)      (null)      (null)           (null)    (null)                      3                                                                7749     (null)      0.00                       (null)                      35.00                      (null)                      (null)        (null)     0.45                                                             (null)          (null)                                                                        (null)          (null)          (null)      (null)         (null)          (null)                   (null)      (null)       004             (null)         (null)      (null)            (null)      (null)                   (null)          (null)                     0.00                       (null)                     (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      IBK              0            (null)      (null)               (null)                     (null)                     (null)                     137984                         ABCBIENES S.A.                                                                                                           (null)    Apr 29 2022  2:16PM         (null)         0           (null)           (null)        (null)          (null)   (null)            0000542333                     26366893                       0            

declare
@w_return  int
begin
 exec @w_return = dbo.pa_pg_pval_rev_core
@e_empresa	 = '7749',
@e_suministro	 = '77846',
@e_canal	 = 'IBK',
@e_usuario   	 = 'ope998',
@e_identificacion= '',
@e_fecha	 = '04/29/2022',
@t_debug     	 = 'N',
@t_file      	 = null,
@e_servicio   	 = '01' 
print '%1!' , @w_return
end
--901422


--------------SEGUIMIENTO FINAL CEP------
select ts_tsfecha, ts_referencia ,* from cob_cuentas..cc_tran_servicio where 
ts_tsfecha = '05/13/2022' and ts_causa = '7749'

ts_tsfecha                  ts_referencia   ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
--------------------------- --------------- ------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
May 13 2022 12:00AM         0002321042      41380393      0              3215                NOR      May 13 2022 12:00AM         (null)   ope998                                                           term24                                                           5      N             (null)      N          L         BOLIVSRV                       0002321042      (null)        0             (null)      5005070292               1         0          (null)     (null)                      (null)      (null)        (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      (null)  (null)       1         (null)      (null)      (null)      (null)           (null)    (null)                      3                                                                7749     (null)      0.00                       (null)                      8.00                       (null)                      (null)        (null)     0.45                                                             (null)          (null)                                                                        (null)          (null)          (null)      (null)         (null)          (null)                   (null)      (null)       004             (null)         (null)      (null)            (null)      (null)                   (null)          (null)                     0.00                       (null)                     (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      IBK              0            (null)      (null)               (null)                     (null)                     (null)                     138039                         ABCBIENES S.A.                                                                                                           (null)    May 13 2022 11:30AM         (null)         0           (null)           (null)        (null)          (null)   (null)            0000542333                     26366893                       0            


declare
@w_return  int
begin
 exec @w_return = dbo.pa_pg_pval_rev_core
@e_empresa	 = '7749',
@e_suministro	 = '2321042',
@e_canal	 = 'IBK',
@e_usuario   	 = 'ope998',
@e_identificacion= '2022',
@e_fecha	 = '05/13/2022',
@t_debug     	 = 'N',
@t_file      	 = null,
@e_servicio   	 = '01' 
print '%1!' , @w_return
end
--901422