select ts_hora, * from cob_cuentas..cc_tran_servicio hs where ts_tsfecha = '08/05/2022' and ts_causa = '19574'

ts_hora                     ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
--------------------------- ------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
--REVERSO
Aug 5 2022  2:55PM          53691739      0              62688                        Aug 5 2022 12:00AM          (null)   ope998                                                           term24                                                           5      S             53679766    (null)     L         BOLIVSRV                       0993696714      (null)        0             (null)      5005070292               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Aug 5 2022 12:00AM                                                                           19574    (null)      0.00                       (null)                      30.00                      (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   53691739                 (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Aug 5 2022  2:55PM          (null)         53691739    (null)           (null)        (null)          (null)   (null)                                                                          0            
--PAGO
Aug 5 2022  2:55PM          53679766      0              62688                        Aug 5 2022 12:00AM          (null)   ope998                                                           term24                                                           5      N             0           (null)     L         BOLIVSRV                       0993696714      (null)        0             (null)      5005070292               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Aug 5 2022 12:00AM                                                                           19574    (null)      0.00                       (null)                      30.00                      (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   53679766                 (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Aug 5 2022  2:55PM          (null)         53679766    (null)           (null)        (null)          (null)   (null)                                                                          0            


select tm_hora ,tm_valor, tm_tsn,* from cob_cuentas..cc_tran_monet where
tm_cta_banco = '5005070292'
and tm_fecha ='2022/08/05'
and tm_valor = 30.00
order by tm_hora


tm_hora                     tm_valor                   tm_tsn      tm_fecha                    tm_secuencial tm_cod_alterno tm_tipo_tran tm_filial tm_oficina tm_usuario                     tm_terminal tm_rol tm_correccion tm_sec_correccion tm_origen tm_nodo                                                          tm_reentry tm_fecha_ult_mov            tm_oficina_pago tm_cta_banco             tm_cheque   tm_valor                   tm_chq_propios             tm_chq_locales             tm_chq_ot_plazas           tm_remoto_ssn tm_moneda tm_efectivo                tm_tipo tm_signo tm_indicador tm_causa tm_departamento tm_ctabanco_dep          tm_prod_dep tm_l24h                    tm_remesas                 tm_contratado              tm_ocasional               tm_saldo_contable          tm_saldo_disponible        tm_banco tm_ctadestino            tm_tipo_xfer tm_tasa_interes          tm_tasa_impuesto         tm_tasa_solca            tm_tasa_comision         tm_valor_interes           tm_valor_impuesto          tm_valor_solca             tm_valor_comision          tm_tarjeta_atm           tm_hora                     tm_beneficiario                tm_oficina_cta tm_tsn      tm_tipo_contable tm_campo_alt_uno               tm_campo_alt_dos               tm_ubicacion tm_canal 
--------------------------- -------------------------- ----------- --------------------------- ------------- -------------- ------------ --------- ---------- ------------------------------ ----------- ------ ------------- ----------------- --------- ---------------------------------------------------------------- ---------- --------------------------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- ------------- --------- -------------------------- ------- -------- ------------ -------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------- ------------------------ ------------ ------------------------ ------------------------ ------------------------ ------------------------ -------------------------- -------------------------- -------------------------- -------------------------- ------------------------ --------------------------- ------------------------------ -------------- ----------- ---------------- ------------------------------ ------------------------------ ------------ -------- 
--PAGO
Aug 5 2022  2:54PM          30.00                      53679766    Aug 5 2022 12:00AM          899200976     0              3050         1         0          ope998                         term24      5      N             (null)            L         BOLIVSRV                                                         N          (null)                      (null)          5005070292               0           30.00                      (null)                     (null)                     (null)                     (null)        1         (null)                     (null)  D        1            524      1               (null)                   (null)      (null)                     (null)                     (null)                     (null)                     443,021.88                 443,021.88                 (null)   0993696714               (null)       (null)                   (null)                   (null)                   (null)                   (null)                     (null)                     (null)                     (null)                     (null)                   Aug 5 2022  2:54PM          0993696714                     50             53679766    2                (null)                         (null)                         0            (null)   
--REVERSO
Aug 5 2022  2:54PM          30.00                      53691739    Aug 5 2022 12:00AM          437519820     0              3050         1         0          ope998                         term24      5      S             (null)            L         BOLIVSRV                                                         N          (null)                      (null)          5005070292               53679766    30.00                      (null)                     (null)                     (null)                     (null)        1         (null)                     (null)  D        1            524      1               (null)                   (null)      (null)                     (null)                     (null)                     (null)                     443,051.88                 443,051.88                 (null)   0993696714               (null)       (null)                   (null)                   (null)                   (null)                   (null)                     (null)                     (null)                     (null)                     (null)                   Aug 5 2022  2:54PM          0993696714                     50             53691739    2                (null)                         (null)                         0            (null)   




SELECT cc_disponible, * FROM cob_cuentas..cc_ctacte where cc_cta_banco = '5005070292'
--443,051.88




------------------------------
------------------------------
--------CUENTA AHORRO---------
------------------------------
------------------------------
select ts_hora, * from cob_cuentas..cc_tran_servicio hs where ts_tsfecha = '08/05/2022' and ts_secuencial in(55757039,55767209)


ts_hora                     ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
--------------------------- ------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
--PAGO
Aug 5 2022  3:29PM          55757039      0              62688                        Aug 5 2022 12:00AM          (null)   ope998                                                           term24                                                           5      N             0           (null)     L         BOLIVSRV                       0991788310      (null)        0             (null)      0002943804               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Aug 5 2022 12:00AM                                                                           19574    (null)      0.00                       (null)                      30.00                      (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   55757039                 (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Aug 5 2022  3:29PM          (null)         55757039    (null)           (null)        (null)          (null)   (null)                                                                          0            
--REVERSO
Aug 5 2022  3:29PM          55767209      0              62688                        Aug 5 2022 12:00AM          (null)   ope998                                                           term24                                                           5      S             55757039    (null)     L         BOLIVSRV                       0991788310      (null)        0             (null)      0002943804               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Aug 5 2022 12:00AM                                                                           19574    (null)      0.00                       (null)                      30.00                      (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   55767209                 (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Aug 5 2022  3:29PM          (null)         55767209    (null)           (null)        (null)          (null)   (null)                                                                          0            

select tm_hora ,tm_valor,* from cob_ahorros..ah_tran_monet where
tm_cta_banco = '0002943804' --ts_cta_banco
and tm_fecha ='2022/08/05'
and tm_valor = 30.00
order by tm_hora

tm_hora                     tm_valor                   tm_fecha                    tm_secuencial tm_cod_alterno tm_tipo_tran tm_filial tm_oficina tm_usuario                     tm_terminal tm_correccion tm_sec_correccion tm_origen tm_nodo                                                          tm_reentry tm_signo tm_fecha_ult_mov            tm_cta_banco             tm_valor                   tm_chq_propios             tm_chq_locales             tm_chq_ot_plazas           tm_remoto_ssn tm_moneda tm_efectivo                tm_indicador tm_causa tm_departamento tm_saldo_lib               tm_saldo_contable          tm_saldo_disponible        tm_saldo_interes           tm_fecha_efec               tm_interes                 tm_control  tm_ctadestino            tm_tipo_xfer tm_cheque   tm_val_cheque              tm_banco tm_valor_comision          tm_hora                     tm_tarjeta               tm_oficina_cta tm_tsn      tm_depto tm_valor_impuesto          tm_rol tm_ubicacion tm_canal 
--------------------------- -------------------------- --------------------------- ------------- -------------- ------------ --------- ---------- ------------------------------ ----------- ------------- ----------------- --------- ---------------------------------------------------------------- ---------- -------- --------------------------- ------------------------ -------------------------- -------------------------- -------------------------- -------------------------- ------------- --------- -------------------------- ------------ -------- --------------- -------------------------- -------------------------- -------------------------- -------------------------- --------------------------- -------------------------- ----------- ------------------------ ------------ ----------- -------------------------- -------- -------------------------- --------------------------- ------------------------ -------------- ----------- -------- -------------------------- ------ ------------ -------- 
Aug 5 2022  3:29PM          30.00                      Aug 5 2022 12:00AM          701316922     0              4264         (null)    0          ope998                         term24      N             (null)            L         BOLIVSRV                                                         N          D        (null)                      0002943804               30.00                      (null)                     (null)                     (null)                     (null)        1         (null)                     1            524      (null)          (null)                     99,647.00                  99,647.00                  (null)                     (null)                      (null)                     (null)      0991788310               (null)       0           (null)                     (null)   (null)                     Aug 5 2022  3:29PM          0991788310               0              55757039    71       0.00                       5      0            (null)   
Aug 5 2022  3:29PM          30.00                      Aug 5 2022 12:00AM          1757673391    0              4264         (null)    0          ope998                         term24      S             (null)            L         BOLIVSRV                                                         N          D        (null)                      0002943804               30.00                      (null)                     (null)                     (null)                     (null)        1         (null)                     1            524      (null)          (null)                     99,677.00                  99,677.00                  (null)                     (null)                      (null)                     (null)      0991788310               (null)       55757039    (null)                     (null)   (null)                     Aug 5 2022  3:29PM          0991788310               0              55767209    71       0.00                       5      0            (null)   


SELECT ah_disponible, * FROM cob_ahorros..ah_cuenta where ah_cta_banco = '0002943804'
--99,677.00
