kind: Service
apiVersion: v1
metadata:
  name: rec-ecutel
  namespace: bb-dev-recaudosempresas
  labels:
    app: rec-ecutel
    app.kubernetes.io/component: rec-ecutel
    app.kubernetes.io/instance: rec-ecutel
    app.kubernetes.io/name: openjdk-11
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    deploymentconfig: rec-ecutel
  sessionAffinity: None
