/**************************************************************************/
/* Archivo:            cckb0053.sql		                                    */
/* Objeto:             OTC_M_CONVENIO,OTC_D_SERVICIO, OTC_M_EMPRESA       */
/* Base de datos:      DB_OTC                                     		    */
/* Producto:           Recaudaciones                                      */
/* Disenado por:       Kevin Bastidas                                     */
/* Fecha de escritura: 29/06/2023                                         */
/* Descripcion:        Script para agregar tipo servicio Trnsf. Dominio   */
/**************************************************************************/
/*                            MODIFICACIONES                              */
/*   FECHA     TAREA             AUTOR                  RAZON             */
/*29/06/2023  RECMPS-1351		Kevin Bastidas      Emision inicial           */
/**************************************************************************/
  set serveroutput on;

DECLARE
  LV_MSG_INI VARCHAR2(100) := 'INICIO SCRIPT';
  LV_MSG_FIN VARCHAR2(100) := 'FINAL SCRIPT';
  LN_CODIGO_EMPRESA         NUMBER := 0;
  LN_CODIGO_GRUPO           NUMBER := 0;
  LN_CODIGO_CONVENIO        NUMBER := 0;
  LN_CODIGO_SERVICIO        NUMBER := 0;
  LN_CODIGO_CANAL           NUMBER := 0;
  LN_CODIGO_IDENTIFICADOR   NUMBER := 0;
  LN_CODIGO_PUNTOFINAL      NUMBER := 0;
  LN_CODIGO_FLUJO           NUMBER := 0;
  LN_CODIGO_FLUJOENRIQ      NUMBER := 0;
  LN_GRUPO_SERVICIO			NUMBER := 8; 
  LV_COBIS_EMPRESA			VARCHAR2(15)  := 'SRI-TRNF-DOM';
  LV_EMPRESA 				VARCHAR2(50) := 'Transferencia Dominio';
  LV_RUC_EMPRESA			VARCHAR2(15) := '0999999999999';
  LV_FLUJO_SOA				VARCHAR2(4)  := 'RMS';
  LV_PUNTO_FINAL 			VARCHAR2(50) := 'Recaudaciones/Microservicio';
  LV_REPOSITORIO_PETICION	VARCHAR2(50) := '/opt/microservices/transformaciones';
  LV_EMPRESA_XSL			VARCHAR2(50) := 'RMS_TRNSF_DOMINIO';
BEGIN
  
  DBMS_OUTPUT.put_line(LV_MSG_INI);

  DBMS_OUTPUT.put_line('OBTENIENDO SECUENCIAS MAXIMAS TABLAS OTC');
  -- OBTENER MAXIMO CODIGO TABLAS OTC
  select MAX(EMP_ID)+1 into LN_CODIGO_EMPRESA from DB_OTC.OTC_M_EMPRESA;      
  -- INSERTAR EN EL SUB MENU SERVICIOS LOGISTICOS
  --select GRP_ID into LN_CODIGO_GRUPO from DB_OTC.OTC_D_SERVICIO WHERE SRV_ID = '29';
  select MAX(GRP_ID)+1 into LN_CODIGO_GRUPO from DB_OTC.OTC_M_GRUPO_SERVICIO; 
  select MAX(CNV_ID)+1 into LN_CODIGO_CONVENIO from DB_OTC.OTC_M_CONVENIO;
  select MAX(SRV_ID)+1 into LN_CODIGO_SERVICIO from DB_OTC.OTC_D_SERVICIO;
  select MAX(SC_ID)+1 into LN_CODIGO_CANAL from DB_OTC.OTC_D_SERVICIO_CANAL;
  select MAX(TID_ID)+1 into LN_CODIGO_IDENTIFICADOR from DB_OTC.OTC_M_TIPO_IDENTIFICADOR;
  select MAX(END_ID)+1 into LN_CODIGO_PUNTOFINAL from DB_OTC.OTC_M_PUNTO_FINAL;
  select MAX(FLU_ID)+1 into LN_CODIGO_FLUJO from DB_OTC.OTC_M_FLUJO;
  select MAX(FSE_ID)+1 into LN_CODIGO_FLUJOENRIQ from DB_OTC.OTC_D_FLUJO_SERV_ENRIQ;

    Insert into DB_OTC.OTC_M_EMPRESA (EMP_ID,EMP_IDENTIFICACION,EMP_NOMBRE,EMP_CODIGO,EMP_DESCRIPCION, EMP_BANCO) 
    values (LN_CODIGO_EMPRESA,LV_RUC_EMPRESA,LV_EMPRESA,'9718',LV_EMPRESA, null);
    DBMS_OUTPUT.put_line('INSERTAR EMPRESA OK');

    Insert into DB_OTC.OTC_M_GRUPO_SERVICIO (GRP_ID,EMP_ID,CT_ID_TIPO_BANCA,CT_ID_TIPO_SERV,GRP_CONVENIO_VISIBLE,GRP_MATRICULABLE,GRP_MATRIC_MULTIPLE,GRP_VALIDABLE) 
    values (LN_CODIGO_GRUPO,LN_CODIGO_EMPRESA,'1',LN_GRUPO_SERVICIO,'1','1','0','0');
    DBMS_OUTPUT.put_line('INSERTAR GRUPO SERVICIO OK');

    --*** REEMPLAZAR CODIGO DE LA EMPRESA
    --1: CONVENIOS--
    Insert into DB_OTC.OTC_M_CONVENIO (CNV_ID,CNV_CODIGO,CNV_VISIBLE,CNV_ETIQUETA_CODIGO) 
    values (LN_CODIGO_CONVENIO,LV_COBIS_EMPRESA,'1',LV_EMPRESA);
    DBMS_OUTPUT.put_line('INSERTAR CONVENIO OK');
    
    --*** REEMPLAZAR NOMBRE DE LA EMPRESA
    --2: SERVICIOS--
    Insert into DB_OTC.OTC_D_SERVICIO (SRV_ID,SRV_NOMBRE,GRP_ID,CNV_ID) 
    values (LN_CODIGO_SERVICIO,LV_EMPRESA,LN_CODIGO_GRUPO,LN_CODIGO_CONVENIO);
    --DBMS_OUTPUT.put_line('INSERTAR SERVICIO OK');
    
    --3:SERVICIO CANAL--
    Insert into DB_OTC.OTC_D_SERVICIO_CANAL (SC_ID,SRV_ID,CAN_ID) 
    values (DB_OTC.SQ_DSRVCANAL_SCID.NEXTVAL,LN_CODIGO_SERVICIO,'5');
    --DBMS_OUTPUT.put_line('INSERTAR SERVICIO CANAL OK');
    
    
    --*** REEMPLAZAR RUTA DEL PROXY LOCAL A CONSUMIR Y NOMBRES DE LAS TRANSFORMACIONES
    --*** EN CASO DE NECESITAR EL REVERSO AUMENTAR EN EL SCRIPT
    --5:ENDPOINT --
    Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL,LV_EMPRESA || ' CONSULTA',LV_PUNTO_FINAL,'Consultar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION,LV_EMPRESA_XSL || '_C_IN.xsl', LV_EMPRESA_XSL || '_C_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL CONSULTA OK');
    
	Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL+1,LV_EMPRESA || ' PAGO',LV_PUNTO_FINAL,'Pagar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION, LV_EMPRESA_XSL || '_P_IN.xsl', LV_EMPRESA_XSL || '_P_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL PAGAR OK');
	
	Insert into DB_OTC.OTC_M_PUNTO_FINAL (END_ID,END_NOMBRE,END_PUNTO_FINAL,END_OPERACION,END_REPOSITORIO_PETICION,END_REPOSITORIO_RESPUESTA,END_PETICION,END_RESPUESTA, END_AMBIENTE) 
    values (LN_CODIGO_PUNTOFINAL+2,LV_EMPRESA || ' REVERSO',LV_PUNTO_FINAL,'Reversar',LV_REPOSITORIO_PETICION,LV_REPOSITORIO_PETICION, LV_EMPRESA_XSL || '_R_IN.xsl', LV_EMPRESA_XSL || '_R_OUT.xsl',LV_FLUJO_SOA);
    DBMS_OUTPUT.put_line('INSERTAR PUNTO FINAL PAGAR OK');
        
    --** CONSIDERACIONES:
    --** 22 => CONSULTA
    --** 6  => PAGO
	  --** 23 => REVERSO
    --6:FLUJO-- 
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO,LN_CODIGO_PUNTOFINAL,LN_CODIGO_CONVENIO,'22');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO CONSULTA OK');
	
    Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+1,LN_CODIGO_PUNTOFINAL+1,LN_CODIGO_CONVENIO,'6');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO PAGO OK');
	
	Insert into DB_OTC.OTC_M_FLUJO (FLU_ID,END_ID,CNV_ID,CTD_ID_OPERACION) 
    values (LN_CODIGO_FLUJO+2,LN_CODIGO_PUNTOFINAL+2,LN_CODIGO_CONVENIO,'23');
    DBMS_OUTPUT.put_line('INSERTAR FLUJO REVERSO OK');
    
    -- 7:FLUJO SERVICIO ENRIQ --
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ,'1',LN_CODIGO_FLUJO);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ CONSULTA OK');
	
    Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+1,'1',LN_CODIGO_FLUJO+1);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ PAGO OK');
	
	Insert into DB_OTC.OTC_D_FLUJO_SERV_ENRIQ (FSE_ID,ES_ID,FLU_ID) 
    values (LN_CODIGO_FLUJOENRIQ+2,'1',LN_CODIGO_FLUJO+2);
    DBMS_OUTPUT.put_line('INSERTAR FLUJO ENRIQ REVERSO OK');

    
    --CONFIRMAR
    COMMIT;
    
    DBMS_OUTPUT.put_line('******************* DATOS INSERTADOS **************************');
    DBMS_OUTPUT.put_line('CODIGO EMPRESA : '||LN_CODIGO_EMPRESA);
    DBMS_OUTPUT.put_line('CODIGO GRUPO SERVICIO : '||LN_CODIGO_GRUPO);
    DBMS_OUTPUT.put_line('CODIGO CONVENIO : '||LN_CODIGO_CONVENIO);
    DBMS_OUTPUT.put_line('CODIGO SERVICIO : '||LN_CODIGO_SERVICIO);
    DBMS_OUTPUT.put_line('CODIGO SERVICIO CANAL : '||LN_CODIGO_CANAL);
    DBMS_OUTPUT.put_line('CODIGO IDENTIFICADOR : '||LN_CODIGO_IDENTIFICADOR);
    DBMS_OUTPUT.put_line('CODIGO PUNTO FINAL CONSULTAR : '||LN_CODIGO_PUNTOFINAL);
    DBMS_OUTPUT.put_line('CODIGO PUNTO FINAL PAGAR : '||TO_CHAR(LN_CODIGO_PUNTOFINAL+1));
	  DBMS_OUTPUT.put_line('CODIGO PUNTO FINAL REVERSAR : '||TO_CHAR(LN_CODIGO_PUNTOFINAL+2));
    DBMS_OUTPUT.put_line('CODIGO FLUJO CONSULTA : '||LN_CODIGO_FLUJO);
    DBMS_OUTPUT.put_line('CODIGO FLUJO PAGO : '||TO_CHAR(LN_CODIGO_FLUJO+1));
	  DBMS_OUTPUT.put_line('CODIGO FLUJO REVERSO : '||TO_CHAR(LN_CODIGO_FLUJO+2));
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ CONSULTA : '||LN_CODIGO_FLUJOENRIQ);
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ PAGO : '||TO_CHAR(LN_CODIGO_FLUJOENRIQ+1));       
    DBMS_OUTPUT.put_line('CODIGO FLUJO ENRIQ REVERSO : '||TO_CHAR(LN_CODIGO_FLUJOENRIQ+2));   	
    DBMS_OUTPUT.put_line(LV_MSG_FIN);
 
    
  EXCEPTION
  WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.put_line(DBMS_UTILITY.format_error_stack);
  
END;
/

	select CNV_CODIGO from DB_OTC.OTC_M_CONVENIO  where CNV_ETIQUETA_CODIGO = 'Transferencia Dominio';
	select SRV_NOMBRE from DB_OTC.OTC_D_SERVICIO where SRV_NOMBRE    = 'Transferencia Dominio';
	select END_NOMBRE from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'Transferencia Dominio CONSULTA';
	select END_NOMBRE from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'Transferencia Dominio PAGO';
	select END_NOMBRE from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'Transferencia Dominio REVERSO';

/*
INICIO SCRIPT
OBTENIENDO SECUENCIAS MAXIMAS TABLAS OTC
INSERTAR CONVENIO OK
INSERTAR PUNTO FINAL CONSULTA OK
INSERTAR PUNTO FINAL PAGAR OK
INSERTAR PUNTO FINAL PAGAR OK
INSERTAR FLUJO CONSULTA OK
INSERTAR FLUJO PAGO OK
INSERTAR FLUJO REVERSO OK
INSERTAR FLUJO ENRIQ CONSULTA OK
INSERTAR FLUJO ENRIQ PAGO OK
INSERTAR FLUJO ENRIQ REVERSO OK
******************* DATOS INSERTADOS **************************
CODIGO EMPRESA : 478
CODIGO GRUPO SERVICIO : 21
CODIGO CONVENIO : 371
CODIGO SERVICIO : 961
CODIGO SERVICIO CANAL : 2738
CODIGO IDENTIFICADOR : 472
CODIGO PUNTO FINAL CONSULTAR : 227
CODIGO PUNTO FINAL PAGAR : 228
CODIGO PUNTO FINAL REVERSAR : 229
CODIGO FLUJO CONSULTA : 1122
CODIGO FLUJO PAGO : 1123
CODIGO FLUJO REVERSO : 1124
CODIGO FLUJO ENRIQ CONSULTA : 549
CODIGO FLUJO ENRIQ PAGO : 550
CODIGO FLUJO ENRIQ REVERSO : 551
FINAL SCRIPT
*/