<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/xsd/TvCable_1.wsdl"/>
      <rootElement name="MensajeSalidaConsultar" namespace="http://www.bolivariano.com/MensajeTvCable"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../Disco%20D/veinti4online/Proyecto%20Cash/Concentrador%20de%20pagos/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="salidaConsultarDeuda" namespace="http://www.bolivariano.com/mensaje/MensajeOTC"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED MAY 30 16:02:13 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns7="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns1="http://www.bolivariano.com/CoreBB"
                xmlns:ns3="http://www.bolivariano.com/Cuenta"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns13="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns14="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns6="http://www.bolivariano.com/TvCable"
                xmlns:ns18="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns17="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns9="http://www.bolivariano.com/dominio/Servicio"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns0="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd1="http://www.bolivariano.com/MensajeTvCable"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns4="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns10="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns11="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:tns="http://www.bolivariano.com/ws/TvCable/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns12="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns8="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://www.bolivariano.com/Producto"
                xmlns:ns15="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns5="http://www.bolivariano.com/Cliente"
                xmlns:ns16="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap ns1 ns3 wsdl ns6 ns0 xsd1 ns4 tns xsd ns2 ns5 ns7 ns13 ns14 ns18 ns17 ns9 ns10 ns11 ns12 ns8 ns15 ns16 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns16:salidaConsultarDeuda>
      <xsl:choose>
        <xsl:when test="/xsd1:MensajeSalidaConsultar/codigoError!='1' and /xsd1:MensajeSalidaConsultar/codigoError!='0'">
          <ns16:codigoError>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoError"/>
          </ns16:codigoError>
          <ns16:mensajeUsuario>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
          </ns16:mensajeUsuario>
        </xsl:when>
        <xsl:when test="/xsd1:MensajeSalidaConsultar/codigoErrorRemoto='0'">
          <xsl:if test='/xsd1:MensajeSalidaConsultar/TvCable/valorTotalCancelar = 0'>
            <ns16:codigoError>-1</ns16:codigoError>
            <ns16:mensajeUsuario>CLIENTE NO TIENE DEUDA</ns16:mensajeUsuario>
          </xsl:if>
          <xsl:if test='/xsd1:MensajeSalidaConsultar/TvCable/valorTotalCancelar > 0'>
            <ns16:codigoError>0</ns16:codigoError>
            <ns16:mensajeUsuario>
              <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
            </ns16:mensajeUsuario>
          </xsl:if>
        </xsl:when>
        <xsl:when test="/xsd1:MensajeSalidaConsultar/codigoErrorRemoto!='0'">
          <ns16:codigoError>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/codigoErrorRemoto"/>
          </ns16:codigoError>
          <ns16:mensajeUsuario>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/mensajeUsuario"/>
          </ns16:mensajeUsuario>
        </xsl:when>
      </xsl:choose>
      <ns16:datosAdicionales>
        <ns16:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">empresa</xsl:text>
          </codigo>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/TvCable/empresa"/>
          </valor>
          <visible>
            <xsl:text disable-output-escaping="no">false</xsl:text>
          </visible>
        </ns16:datoAdicional>
        <ns16:datoAdicional>
          <codigo>
            <xsl:text disable-output-escaping="no">oficinaPago</xsl:text>
          </codigo>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaConsultar/TvCable/oficinaPago"/>
          </valor>
          <visible>
            <xsl:text disable-output-escaping="no">false</xsl:text>
          </visible>
        </ns16:datoAdicional>
      </ns16:datosAdicionales>
      <ns16:formaPago>
        <xsl:text disable-output-escaping="no">ABONO</xsl:text>
      </ns16:formaPago>	  
      <ns16:montoTotal>
        <xsl:value-of select="/xsd1:MensajeSalidaConsultar/TvCable/valorTotalCancelar"/>
      </ns16:montoTotal>
      <ns16:nombreCliente>
        <xsl:value-of select="/xsd1:MensajeSalidaConsultar/TvCable/nombre"/>
      </ns16:nombreCliente>
    </ns16:salidaConsultarDeuda>
  </xsl:template>
</xsl:stylesheet>
