select * from DB_OTC.OTC_M_EMPRESA  where EMP_CODIGO = '1348';
select * from DB_OTC.OTC_M_CONVENIO  where CNV_CODIGO = '1348';
select * from DB_OTC.OTC_D_SERVICIO where SRV_NOMBRE = '1348';
select * from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'UNIV. CATOLICA DE CUENCA 1348 CONSULTA';
select * from DB_OTC.OTC_M_PUNTO_FINAL where END_NOMBRE = 'UNIV. CATOLICA DE CUENCA 1348 PAGO';
