update cobis..cl_parametro
set pa_datetime = '02/01/2023'
where pa_nemonico = 'FCA06'


select convert(varchar, dateadd(dd, 1, pa_datetime), 101)
from cobis..cl_parametro
where pa_nemonico = 'FCA06'

select count(1) from cob_cuentas_his..cc_his_movimiento
where hm_fecha = '02/02/2023' 
go
select count(1) from cob_ahorros_his..ah_his_movimiento
where hm_fecha = '02/02/2023' 
go
select count(1) from cob_cuentas_his..cc_his_servicio 
where hs_tsfecha = '02/02/2023' 
go
select count(1) from cob_cuentas..cc_tran_servicio_resp
where ts_tsfecha = '02/02/2023'
go


delete from cob_cuentas_his..cc_his_movimiento
where hm_fecha = '02/02/2023' 
go
delete from cob_ahorros_his..ah_his_movimiento
where hm_fecha = '02/02/2023' 
go
delete from cob_cuentas_his..cc_his_servicio 
where hs_tsfecha = '02/02/2023' 
go
delete from cob_cuentas..cc_tran_servicio_resp
where ts_tsfecha = '02/02/2023' 
go

---PASO MONETARIA CORRIENTE A LA HISTORICA
insert into cob_cuentas_his..cc_his_movimiento
select tm_fecha,tm_secuencial,tm_cod_alterno,tm_tipo_tran,tm_filial,tm_oficina,tm_usuario,tm_terminal,tm_rol,tm_correccion,tm_sec_correccion,tm_origen,tm_nodo,tm_reentry,tm_fecha_ult_mov,tm_oficina_pago,tm_cta_banco,tm_cheque,tm_valor,tm_chq_propios,tm_chq_locales,tm_chq_ot_plazas,tm_remoto_ssn,tm_moneda,tm_efectivo,tm_tipo,tm_signo,tm_indicador,tm_causa,tm_departamento,tm_ctabanco_dep,tm_prod_dep,tm_l24h,tm_remesas,tm_contratado,tm_ocasional,tm_saldo_contable,tm_saldo_disponible,tm_banco,tm_ctadestino,tm_tipo_xfer,tm_tasa_interes,tm_tasa_impuesto,tm_tasa_solca,tm_tasa_comision,tm_valor_interes,tm_valor_impuesto,tm_valor_solca,tm_valor_comision,tm_tarjeta_atm,tm_hora,tm_beneficiario,tm_oficina_cta,tm_tsn,0,tm_tipo_contable,tm_campo_alt_uno,tm_campo_alt_dos,tm_ubicacion,tm_canal
from cob_cuentas..cc_tran_monet
where tm_tsn in (133067041,133067061,918007433,133067498,1766338701)

--PASO MONETARIO AHORRO A LA HISTORICA
--insert into cob_ahorros_his..ah_his_movimiento
--select tm_cta_banco,tm_fecha,0,             tm_secuencial,tm_cod_alterno,tm_tipo_tran,tm_filial,tm_oficina,tm_usuario,tm_terminal,tm_correccion,tm_sec_correccion,tm_origen,tm_nodo,tm_reentry,tm_signo,tm_fecha_ult_mov,tm_valor,tm_chq_propios,tm_chq_locales,tm_chq_ot_plazas,tm_remoto_ssn,tm_moneda,tm_efectivo,tm_indicador,tm_causa,tm_departamento,tm_saldo_lib,tm_saldo_contable,tm_saldo_disponible,tm_saldo_interes,tm_fecha_efec,tm_interes,tm_control,tm_ctadestino,tm_tipo_xfer,tm_valor_comision,tm_hora,tm_tarjeta,tm_oficina_cta,tm_tsn,tm_cheque,tm_val_cheque,tm_banco,tm_valor_impuesto,tm_rol,tm_ubicacion,tm_canal
--from cob_ahorros..ah_tran_monet
--where tm_fecha = '10/31/2022'	--Fecha solicitada
--and tm_tsn in (49551906,49864609,50884923,51011429,51740339)

--PASO TABLA DE SERVICIOS A LA HISTORICA
insert into cob_cuentas_his..cc_his_servicio 
select * from cob_cuentas..cc_tran_servicio
where ts_secuencial in (133067041,133067061,133067498,56342136)

--PASO TABLA DE SERVICIOS A LA DE RESPALDO
insert into cob_cuentas..cc_tran_servicio_resp
select * from cob_cuentas..cc_tran_servicio
where ts_secuencial in (133067041,133067061,133067498,56342136)

select * from cob_cuentas_his..cc_his_servicio  where hs_tsfecha = '02/02/2023'  
select * from cob_cuentas_his..cc_his_servicio where hs_tsfecha = '02/02/2023'

update cobis..cl_catalogo
set valor = 'KBASTIDZ@BOLIVARIANO.COM'
from cobis..cl_catalogo a, cobis..cl_tabla b
where a.tabla = b.codigo
and b.tabla = 'cc_mails_a06'
and a.codigo = '01'
and a.estado = 'V'


Select * from cobis..cl_catalogo a, cobis..cl_tabla b
where a.tabla = b.codigo
and b.tabla = 'cc_mails_a06'
and a.codigo = '01'
and a.estado = 'V'


SELECT * from
cob_super..cc_detalle_a06
where cd_fecha_corte = '02/02/2023'
and (cd_numero_trans + cd_monto_base ) >0
order by cd_tipo_servicio, cd_canal, cd_tipo_producto

cd_producto cd_fecha_corte              cd_canal cd_tipo_servicio cd_tipo_producto cd_descripcion                                                                                       cd_tipo_tarjeta cd_clase_tarjeta cd_tipo_tarifa cd_tipo_cliente cd_numero_trans cd_tarifa                cd_ingreso_total         cd_tasa_ponderada          cd_cta_contable      cd_prop_canal cd_cod_provincia cd_cod_canton cd_cargo_porcentaje        cd_ingreso_neto            cd_monto_base              cd_base_imponible          cd_iva_pagado              
----------- --------------------------- -------- ---------------- ---------------- ---------------------------------------------------------------------------------------------------- --------------- ---------------- -------------- --------------- --------------- ------------------------ ------------------------ -------------------------- -------------------- ------------- ---------------- ------------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- 
3           Feb 2 2023 12:00AM          O        TD00371007                        Recaudaciones varias Empresariales                                                                   (null)          (null)           TD                             3               0.89                     0.8                      (null)                     540708               P             09               01            0.00                       0.00                       0.80                       0.80                       0.10                       


--ANALISIS LLAMA AL SP
cob_super..sp_helptext sp_obtener_ah_his_mov, null, null, showsql


--REALIZAR DELETE
--delete from cob_ahorros_acum..ah_his_mov_a06
--delete cob_super..cc_detalle_a06


cd /fuentes/cobis/cuentas/ctacte/batch/fuentes
operadorRec
ClvOpeRec++1
sqr -debug -Mvar cccrea06.sqr crodrigm/Pcrouez+14
do ParamS '02/02/2023'	--Fecha solicitada mm/dd/aaaa
do ParamN 1
do ParamS N



------------  TRANSACCIONES ---------------------------
select * from cob_cuentas..cc_tran_servicio where ts_secuencial in(133067041,133067061,133067498,56342136)
select * from cob_cuentas..cc_tran_monet where tm_secuencial in (133067041,133067061,918007433,133067498,1766338701)

tm_fecha                    tm_secuencial tm_cod_alterno tm_tipo_tran tm_filial tm_oficina tm_usuario                     tm_terminal tm_rol tm_correccion tm_sec_correccion tm_origen tm_nodo                                                          tm_reentry tm_fecha_ult_mov            tm_oficina_pago tm_cta_banco             tm_cheque   tm_valor                   tm_chq_propios             tm_chq_locales             tm_chq_ot_plazas           tm_remoto_ssn tm_moneda tm_efectivo                tm_tipo tm_signo tm_indicador tm_causa tm_departamento tm_ctabanco_dep          tm_prod_dep tm_l24h                    tm_remesas                 tm_contratado              tm_ocasional               tm_saldo_contable          tm_saldo_disponible        tm_banco tm_ctadestino            tm_tipo_xfer tm_tasa_interes          tm_tasa_impuesto         tm_tasa_solca            tm_tasa_comision         tm_valor_interes           tm_valor_impuesto          tm_valor_solca             tm_valor_comision          tm_tarjeta_atm           tm_hora                     tm_beneficiario                tm_oficina_cta tm_tsn      tm_tipo_contable tm_campo_alt_uno               tm_campo_alt_dos               tm_ubicacion tm_canal 
--------------------------- ------------- -------------- ------------ --------- ---------- ------------------------------ ----------- ------ ------------- ----------------- --------- ---------------------------------------------------------------- ---------- --------------------------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- ------------- --------- -------------------------- ------- -------- ------------ -------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------- ------------------------ ------------ ------------------------ ------------------------ ------------------------ ------------------------ -------------------------- -------------------------- -------------------------- -------------------------- ------------------------ --------------------------- ------------------------------ -------------- ----------- ---------------- ------------------------------ ------------------------------ ------------ -------- 
Feb 2 2023 12:00AM          133067041     0              4435         (null)    0          crodrigm                       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               0           9,610.75                   0.00                       0.00                       0.00                       (null)        1         9,610.75                   (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     161,067.41                 27,789.41                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:27PM          0990033110001                  0              133067041   1                (null)                         (null)                         0            VEN      
Feb 2 2023 12:00AM          133067061     0              4435         (null)    0          crodrigm                       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               5           0.00                       0.00                       39,643.00                  0.00                       (null)        1         0.00                       (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     200,710.41                 27,789.41                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:29PM          0991257721001                  0              133067061   1                (null)                         (null)                         0            VEN      
Feb 2 2023 12:00AM          133067498     0              4435         (null)    50         crodrigm                       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               0           4,243.73                   0.00                       0.00                       0.00                       (null)        1         0.00                       (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     204,954.14                 32,033.14                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:49PM          0993241539001                  0              133067498   1                (null)                         (null)                         600          VEN      
Feb 2 2023 12:00AM          918007433     0              3050         (null)    50         crodrigm                       GRP021041   244    N             (null)            L         SRVDESA2                                                         N          (null)                      (null)          0000088024               0           4,243.73                   (null)                     (null)                     (null)                     (null)        1         (null)                     (null)  D        1            779      1               (null)                   (null)      (null)                     (null)                     (null)                     (null)                     85,430.96                  2,769.03                   (null)   0993241539001            (null)       (null)                   (null)                   (null)                   (null)                   (null)                     (null)                     (null)                     (null)                     (null)                   Feb 2 2023  3:49PM          0993241539001                  0              133067498   1                (null)                         (null)                         600          (null)   
Feb 2 2023 12:00AM          1766338701    0              3050         (null)    0          sa                             consola     1      N             (null)            L         BOLIVSRV                                                         N          (null)                      (null)          0009002638               3           0.90                       (null)                     (null)                     (null)                     (null)        1         (null)                     (null)  D        1            778      1               (null)                   (null)      (null)                     (null)                     (null)                     (null)                     270,302.52                 97,381.52                  (null)   (null)                   (null)       (null)                   (null)                   (null)                   (null)                   (null)                     (null)                     (null)                     (null)                     (null)                   Feb 8 2023  3:39PM          (null)                         0              (null)      1                (null)                         (null)                         (null)       (null)   

ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
56342136      0              3188                N        Feb 2 2023 12:00AM          (null)   sa                                                               consola                                                          (null) N             (null)                 L         (null)                         (null)          (null)        (null)        (null)      0009002638               1         0          (null)     (null)                      (null)      (null)        S         (null)          (null)                                                                                                                   (null)   (null)       (null)      (null)  (null)       1         (null)      (null)      (null)      (null)           (null)    (null)                      (null)                                                           778      (null)      0.10                       (null)                      0.90                       (null)                      (null)        (null)     (null)                                                           (null)          (null)       (null)                                                           (null)          (null)          (null)      (null)         (null)          (null)                   (null)      (null)       (null)          (null)         (null)      (null)            0           (null)                   (null)          (null)                     0.80                       0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               (null)                     (null)                     (null)                     (null)                         (null)                                                                                                                   (null)    Feb 8 2023  3:39PM          (null)         (null)      (null)           (null)        (null)          (null)   (null)            (null)                         (null)                         0            
133067041     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0990033110001   (null)        0             (null)                               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      0.00                       (null)                      0.00                       (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067041                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       9,610.75                   0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Feb 2 2023  3:28PM          (null)         133067041   (null)           (null)        (null)          (null)   (null)                                                                          0            
133067061     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0991257721001   (null)        5             (null)                               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      39,643.00                  (null)                      0.00                       (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067061                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Feb 2 2023  3:29PM          (null)         133067061   (null)           (null)        (null)          (null)   (null)                                                                          0            
133067498     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0993241539001   (null)        0             (null)      0000088024               1         50         (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      0.00                       (null)                      4,243.73                   (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067498                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                    PINTURAS UNIDAS S. A.*****                                                                                               (null)    Feb 2 2023  3:50PM          (null)         133067498   (null)           (null)        (null)          (null)   (null)                                                                          600          

select * from cob_cuentas_his..cc_his_servicio where hs_secuencial in(133067041,133067061,133067498,56342136)
select * from cob_cuentas_his..cc_his_movimiento where hm_secuencial in(133067041,133067061,918007433,133067498,1766338701)


hs_secuencial hs_cod_alterno hs_tipo_transaccion hs_clase hs_tsfecha                  hs_tabla hs_usuario                                                       hs_terminal                                                      hs_rol hs_correccion hs_ssn_corr hs_reentry hs_origen hs_nodo                        hs_referencia   hs_remoto_ssn hs_cheque_rec hs_ctacte   hs_cta_banco             hs_filial hs_oficina hs_oficial hs_fecha_aper               hs_cliente  hs_ced_ruc    hs_estado hs_direccion_ec hs_descripcion_ec                                                                                                        hs_ciclo hs_categoria hs_producto hs_tipo hs_indicador hs_moneda hs_default  hs_tipo_def hs_rol_ente hs_tipo_promedio hs_numero hs_fecha                    hs_autorizante                                                   hs_causa hs_servicio hs_saldo                   hs_fecha_uso                hs_monto                   hs_fecha_ven                hs_filial_aut hs_ofi_aut hs_autoriz_aut                                                   hs_filial_anula hs_ofi_anula hs_autoriz_anula                                                 hs_cheque_desde hs_cheque_hasta hs_chequera hs_num_cheques hs_departamento hs_cta_gir               hs_endoso   hs_cod_banco hs_corresponsal hs_propietario hs_carta    hs_sec_correccion hs_cheque   hs_cta_banco_dep         hs_oficina_pago hs_contratado              hs_valor                   hs_ocasional               hs_banco hs_ccontable         hs_cta_funcionario hs_mercantil hs_cta_asociada          hs_tipocta hs_fecha_eimp               hs_fecha_rimp               hs_fecha_rofi               hs_tipo_chequera hs_stick_imp hs_tipo_imp hs_tarjcred          hs_aporte_iess             hs_descuento_iess          hs_fonres_iess             hs_agente                      hs_nombre                                                                                                                hs_debito hs_hora                     hs_oficina_cta hs_tsn      hs_tipo_contable hs_estado_sob hs_tipo_credito hs_plazo hs_tipo_sobregiro hs_campo_alt_uno               hs_campo_alt_dos               hs_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
56342136      0              3188                N        Feb 2 2023 12:00AM          (null)   sa                                                               consola                                                          (null) N             (null)                 L         (null)                         (null)          (null)        (null)        (null)      0009002638               1         0          (null)     (null)                      (null)      (null)        S         (null)          (null)                                                                                                                   (null)   (null)       (null)      (null)  (null)       1         (null)      (null)      (null)      (null)           (null)    (null)                      (null)                                                           778      (null)      0.10                       (null)                      0.90                       (null)                      (null)        (null)     (null)                                                           (null)          (null)       (null)                                                           (null)          (null)          (null)      (null)         (null)          (null)                   (null)      (null)       (null)          (null)         (null)      (null)            0           (null)                   (null)          (null)                     0.80                       0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               (null)                     (null)                     (null)                     (null)                         (null)                                                                                                                   (null)    Feb 8 2023  3:39PM          (null)         (null)      (null)           (null)        (null)          (null)   (null)            (null)                         (null)                         0            
133067041     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0990033110001   (null)        0             (null)                               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      0.00                       (null)                      0.00                       (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067041                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       9,610.75                   0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Feb 2 2023  3:28PM          (null)         133067041   (null)           (null)        (null)          (null)   (null)                                                                          0            
133067061     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0991257721001   (null)        5             (null)                               1         0          (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      39,643.00                  (null)                      0.00                       (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067061                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   (null)     (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                                                                                                                                             (null)    Feb 2 2023  3:29PM          (null)         133067061   (null)           (null)        (null)          (null)   (null)                                                                          0            
133067498     0              43569               192      Feb 2 2023 12:00AM          (null)   crodrigm                                                         GRP021041                                                        244    N             0           (null)     L         SRVDESA2                       0993241539001   (null)        0             (null)      0000088024               1         50         (null)     (null)                      0                         (null)    (null)          (null)                                                                                                                   (null)   (null)       (null)      L       (null)       1         (null)      N           (null)      (null)           (null)    Feb 2 2023 12:00AM                                                                           20717    (null)      0.00                       (null)                      4,243.73                   (null)                      (null)        (null)     0.00                                                             (null)          (null)       0.00                                                             (null)          (null)          (null)      (null)         (null)          (null)                   133067498                (null)                         (null)      (null)            (null)      (null)                   (null)          0.00                       0.00                       0.00                       (null)   (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       (null)                     (null)                                                    PINTURAS UNIDAS S. A.*****                                                                                               (null)    Feb 2 2023  3:50PM          (null)         133067498   (null)           (null)        (null)          (null)   (null)                                                                          600          

hm_fecha                    hm_secuencial hm_cod_alterno hm_tipo_tran hm_filial hm_oficina hm_usuario     hm_terminal hm_rol hm_correccion hm_sec_correccion hm_origen hm_nodo                                                          hm_reentry hm_fecha_ult_mov            hm_oficina_pago hm_cta_banco             hm_cheque   hm_valor                   hm_chq_propios             hm_chq_locales             hm_chq_ot_plazas           hm_remoto_ssn hm_moneda hm_efectivo                hm_tipo hm_signo hm_indicador hm_causa hm_departamento hm_ctabanco_dep          hm_prod_dep hm_l24h                    hm_remesas                 hm_contratado              hm_ocasional               hm_saldo_contable          hm_saldo_disponible        hm_banco hm_ctadestino            hm_tipo_xfer hm_tasa_interes          hm_tasa_impuesto         hm_tasa_solca            hm_tasa_comision         hm_valor_interes           hm_valor_impuesto          hm_valor_solca             hm_valor_comision          hm_tarjeta_atm           hm_hora                     hm_beneficiario                hm_oficina_cta hm_tsn      hm_transaccion hm_tipo_contable hm_campo_alt_uno               hm_campo_alt_dos               hm_ubicacion hm_canal 
--------------------------- ------------- -------------- ------------ --------- ---------- -------------- ----------- ------ ------------- ----------------- --------- ---------------------------------------------------------------- ---------- --------------------------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- ------------- --------- -------------------------- ------- -------- ------------ -------- --------------- ------------------------ ----------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------------------------- -------- ------------------------ ------------ ------------------------ ------------------------ ------------------------ ------------------------ -------------------------- -------------------------- -------------------------- -------------------------- ------------------------ --------------------------- ------------------------------ -------------- ----------- -------------- ---------------- ------------------------------ ------------------------------ ------------ -------- 
Feb 2 2023 12:00AM          133067041     0              4435         (null)    0          crodrigm       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               0           9,610.75                   0.00                       0.00                       0.00                       (null)        1         9,610.75                   (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     161,067.41                 27,789.41                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:27PM          0990033110001                  0              133067041   0              1                (null)                         (null)                         0            VEN      
Feb 2 2023 12:00AM          133067061     0              4435         (null)    0          crodrigm       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               5           0.00                       0.00                       39,643.00                  0.00                       (null)        1         0.00                       (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     200,710.41                 27,789.41                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:29PM          0991257721001                  0              133067061   0              1                (null)                         (null)                         0            VEN      
Feb 2 2023 12:00AM          133067498     0              4435         (null)    50         crodrigm       GRP021041   244    N             0                 L         SRVDESA2                                                         N          (null)                      (null)          0009002638               0           4,243.73                   0.00                       0.00                       0.00                       (null)        1         0.00                       (null)  C        (null)       2        (null)          (null)                   (null)      (null)                     (null)                     (null)                     (null)                     204,954.14                 32,033.14                  (null)   (null)                   N            (null)                   0.0                      (null)                   (null)                   (null)                     0.00                       (null)                     (null)                     (null)                   Feb 2 2023  3:49PM          0993241539001                  0              133067498   0              1                (null)                         (null)                         600          VEN      
Feb 2 2023 12:00AM          918007433     0              3050         (null)    50         crodrigm       GRP021041   244    N             (null)            L         SRVDESA2                                                         N          (null)                      (null)          0000088024               0           4,243.73                   (null)                     (null)                     (null)                     (null)        1         (null)                     (null)  D        1            779      1               (null)                   (null)      (null)                     (null)                     (null)                     (null)                     85,430.96                  2,769.03                   (null)   0993241539001            (null)       (null)                   (null)                   (null)                   (null)                   (null)                     (null)                     (null)                     (null)                     (null)                   Feb 2 2023  3:49PM          0993241539001                  0              133067498   0              1                (null)                         (null)                         600          (null)   
