ts_tsn   ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta   
------   ------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- 
44624536  44624536      0              4060                F        Apr 11 2022 12:00AM         0        WAP                                                              MOVIL                                                            5      N             44624536    (null)     L         BOLIVSRV                       0982113968      0             0             0           0003538691               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           8456     (null)      0.00                       (null)                      3.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          041365         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      WAP              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         SOLEDISPA BENAVIDEZ GEORGE JORDAN                                                                                        (null)    Apr 11 2022 12:24PM         0              
52636066  52636066      0              4060                F        Apr 11 2022 12:00AM         0        WAP                                                              MOVIL                                                            5      N             52636066    (null)     L         BOLIVSRV                       0982113968      0             0             0           0003538691               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           8456     (null)      0.00                       (null)                      3.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          046659         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      WAP              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         SOLEDISPA BENAVIDEZ GEORGE JORDAN                                                                                        (null)    Apr 11 2022  2:37PM         0              
(66 row(s) affected)


--cob_pagos..pag_t_broadnet_servicio
--ts_secuencial  -> br_sec_bco
--ts_propietario -> br_autoriz
br_codigo       br_valor                   br_fec_cble                 br_fec_proceso              br_sec_bco  br_num_ref br_fecha_trx_local br_hora_trx_local br_est_conciliacion br_usuario br_nombre                                                                        br_tip_trx  br_cta_bco               br_monto_cta               br_tipo_cta br_canal br_empresa br_autoriz 
--------------- -------------------------- --------------------------- --------------------------- ----------- ---------- ------------------ ----------------- ------------------- ---------- -------------------------------------------------------------------------------- ----------- ------------------------ -------------------------- ----------- -------- ---------- ---------- 
0982113968      3.00                       Apr 11 2022 12:00AM         Apr 11 2022 12:00AM         44624536    624536     (null)             122400            S                   WAP        SOLEDISPA BENAVIDEZ GEORGE JORDAN                                                4060        0003538691               3.00                       A           WAP      8456       041365     
0982113968      3.00                       Apr 11 2022 12:00AM         Apr 11 2022 12:00AM         52636066    636066     (null)             143700            S                   WAP        SOLEDISPA BENAVIDEZ GEORGE JORDAN                                                4060        0003538691               3.00                       A           WAP      8456       046659     


(63 row(s) affected)

---pag_t_concilia_broadnet
--co_num_ref -> br_num_ref
--co_num_autoriz -> br_autoriz
co_fec_cble                 co_autoriz_bco co_num_ref co_num_bin  co_valor                   co_fecha_trx                co_hora_trn co_hora_trn_local co_resultado  co_estatus_bco co_estatus_emp_serv co_conciliada co_usuario co_canal co_nombre                                co_celular      co_tip_trx  co_nro_cuenta co_tipo_cuenta co_fecha_archivo            co_fecha_real               co_forma_pago co_debito                  co_empresa co_num_autoriz 
--------------------------- -------------- ---------- ----------- -------------------------- --------------------------- ----------- ----------------- ------------- -------------- ------------------- ------------- ---------- -------- ---------------------------------------- --------------- ----------- ------------- -------------- --------------------------- --------------------------- ------------- -------------------------- ---------- -------------- 
Apr 11 2022 12:00AM         52636066       636066     827624      3.00                       Apr 11 2022 12:00AM         143732      143700            OK            SI             SI                  (null)        WAP        WAP      SOLEDISPA BENAVIDEZ GEORGE JORDAN        0982113968      4060        0003538691    A              Apr 12 2022 12:00AM         Apr 14 2022 12:35PM         (null)        3.00                       8456       046659         
Apr 11 2022 12:00AM         44624536       624536     827624      3.00                       Apr 11 2022 12:00AM         122401      122400            OK            SI             SI                  (null)        WAP        WAP      SOLEDISPA BENAVIDEZ GEORGE JORDAN        0982113968      4060        0003538691    A              Apr 12 2022 12:00AM         Apr 14 2022 12:35PM         (null)        3.00                       8456       041365         
--no encuentra
Apr 11 2022 12:00AM         46650          601819     827624      3.00                       Apr 11 2022 12:00AM         143658      000000            IE            NO             SI                  (null)        (null)     (null)   (null)                                   (null)          (null)      (null)        (null)         Apr 12 2022 12:00AM         (null)                      (null)        (null)                     8456       046650         

(64 row(s) affected)

--cc_l_auxiliar_recarga
ar_celular ar_operadora ar_secuencial            ai_efectivo                ai_debito                  ar_fec_proceso              ar_canal ar_hora                     ar_nombre                      ar_tipo_trx ar_usuario      ar_oficina  ar_ubicacion ai_forma_pago ai_tipo_cuenta ai_cuenta 
---------- ------------ ------------------------ -------------------------- -------------------------- --------------------------- -------- --------------------------- ------------------------------ ----------- --------------- ----------- ------------ ------------- -------------- ----------  
0981537659 8456         52636066.0               0.00                       3.00                       Apr 11 2022 12:00AM         WAP      Apr 11 2022  2:37PM         CONSUMIDOR FINAL               4060        WAP             0           0            DEB           AHO            0003538691
0982113968 8456         44624536.0               0.00                       3.00                       Apr 11 2022 12:00AM         WAP      Apr 11 2022 12:23PM         CONSUMIDOR FINAL               4060        WAP             0           0            DEB           AHO            0003538691
--no encuentra
0981537659 8456         52601819.0               0.00                       3.00                       Apr 11 2022 12:00AM         WAP      Apr 11 2022  2:36PM         CONSUMIDOR FINAL               4060        WAP             0           0            DEB           AHO            0003538691            



select c.co_num_ref, a.ar_secuencial from cob_pagos..cc_l_auxiliar_recarga a inner join cob_pagos..pag_t_concilia_broadnet c on
convert(varchar(15),substring(convert(varchar(15),a.ar_secuencial), 1, patindex('%.%',convert(varchar(15),a.ar_secuencial)))+reverse(convert(varchar(15),convert(int,reverse(substring(convert(varchar(15),a.ar_secuencial), patindex('%.%',convert(varchar(15),a.ar_secuencial))+3,8)))))) = c.co_num_ref 
where 
c.co_valor = a.ai_debito and c.co_fecha_trx = a.ar_fec_proceso and  c.co_num_ref = '601819'

--
select
convert(varchar(15),substring(convert(varchar(15),a.ar_secuencial), 1, patindex('%.%',convert(varchar(15),a.ar_secuencial)))+reverse(convert(varchar(15),convert(int,reverse(substring(convert(varchar(15),a.ar_secuencial), patindex('%.%',convert(varchar(15),a.ar_secuencial))+3,8))))))
from  cob_pagos..cc_l_auxiliar_recarga a where ar_secuencial = 52601819
--601819

select
convert(varchar(15),substring(convert(varchar(15),a.ar_secuencial), 1, patindex('%.%',convert(varchar(15),a.ar_secuencial)))+reverse(convert(varchar(15),convert(int,reverse(substring(convert(varchar(15),a.ar_secuencial), patindex('%.%',convert(varchar(15),a.ar_secuencial))+3,8))))))
from  cob_pagos..cc_l_auxiliar_recarga a where ar_fec_proceso = '04/11/2022' and ar_operadora = 8456


select c.co_num_ref, a.ar_secuencial from cob_pagos..cc_l_auxiliar_recarga a inner join cob_pagos..pag_t_concilia_broadnet c on
convert(varchar(15),substring(convert(varchar(15),a.ar_secuencial), 1, patindex('%.%',convert(varchar(15),a.ar_secuencial)))+reverse(convert(varchar(15),convert(int,reverse(substring(convert(varchar(15),a.ar_secuencial), patindex('%.%',convert(varchar(15),a.ar_secuencial))+3,8)))))) = c.co_num_ref 
where 
c.co_valor = a.ai_debito and c.co_fecha_trx = a.ar_fec_proceso


exec pa_pag_c_concilia_broadnet_s
@e_fecha = '4/11/2022',
@e_empresa = '8456',
@e_siguiente = 0,
@e_estado_bco = 'NO',
@e_estado_emp = 'SI',
@e_forma_pago = null

--------------------------------------TWENTI-----------------------------------------------------------------------------------
select * from cob_cuentas..cc_tran_servicio where ts_causa = '8457' and ts_tsfecha = '04/11/2022'

ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
172888426     0              4062                F        Apr 11 2022 12:00AM         0        WAP                                                              MOVIL                                                            5      N             172888426   (null)     L         BOLIVSRV                       0939293368      0             0             0           0861092521               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           8457     (null)      0.00                       (null)                      3.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          383072         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      WAP              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         BETSY DEL ROCIO QUITO VILLON                                                                                             (null)    Apr 9 2022  8:15PM          0              172888426   (null)           (null)        (null)          (null)   (null)            (null)                         9999999999                     0            

--delete FROM cob_cuentas..cc_tran_servicio where ts_causa = '8457' and ts_secuencial = 172888426
--delete FROM pag_t_concilia_broadnet where co_empresa in('8456', '8457')


select  * from pag_t_concilia_broadnet 
where co_resultado = 'IE' and co_estatus_bco = 'NO' and  co_estatus_emp_serv = 'SI' and co_fecha_trx = '04/11/2022' and co_empresa = '8457'

select * from cob_pagos..cc_l_auxiliar_recarga where ar_fec_proceso = '04/11/2022' and ar_secuencial = 172888426.0

--cc_tran_servicio -delete
ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
172888426     0              4062                F        Apr 11 2022 12:00AM         0        WAP                                                              MOVIL                                                            5      N             172888426   (null)     L         BOLIVSRV                       0939293368      0             0             0           0861092521               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           8457     (null)      0.00                       (null)                      3.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          383072         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      WAP              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         BETSY DEL ROCIO QUITO VILLON                                                                                             (null)    Apr 9 2022  8:15PM          0              172888426   (null)           (null)        (null)          (null)   (null)            (null)                         9999999999                     0            

--pag_t_concilia_broadnet
co_fec_cble                 co_autoriz_bco co_num_ref co_num_bin  co_valor                   co_fecha_trx                co_hora_trn co_hora_trn_local co_resultado  co_estatus_bco co_estatus_emp_serv co_conciliada co_usuario co_canal co_nombre                                co_celular      co_tip_trx  co_nro_cuenta co_tipo_cuenta co_fecha_archivo            co_fecha_real               co_forma_pago co_debito                  co_empresa co_num_autoriz 
--------------------------- -------------- ---------- ----------- -------------------------- --------------------------- ----------- ----------------- ------------- -------------- ------------------- ------------- ---------- -------- ---------------------------------------- --------------- ----------- ------------- -------------- --------------------------- --------------------------- ------------- -------------------------- ---------- -------------- 
Apr 11 2022 12:00AM         383072         888426     827688      3.00                       Apr 10 2022 12:00AM         201500      000000            IE            NO             SI                  (null)        (null)     (null)   (null)                                   (null)          (null)      (null)        (null)         Apr 12 2022 12:00AM         (null)                      (null)        (null)                     8457       383072         

--cc_l_auxiliar_recarga
ar_celular ar_operadora ar_secuencial            ai_efectivo                ai_debito                  ar_fec_proceso              ar_canal ar_hora                     ar_nombre                      ar_tipo_trx ar_usuario      ar_oficina  ar_ubicacion ai_forma_pago ai_tipo_cuenta ai_cuenta            ai_resultado    ai_error             ai_fecha_concilia 
---------- ------------ ------------------------ -------------------------- -------------------------- --------------------------- -------- --------------------------- ------------------------------ ----------- --------------- ----------- ------------ ------------- -------------- -------------------- --------------- -------------------- ----------------- 
0978974811 8457         172888426.0              0.00                       3.00                       Apr 11 2022 12:00AM         WAP      Apr 9 2022  8:14PM          CONSUMIDOR FINAL               4062        WAP             0           0            DEB           AHO            0861092521           (null)          (null)               (null)            



--------------------------------------MOVISTAR-----------------------------------------------------------------------------------
--delete FROM pag_t_concilia_broadnet where co_empresa in('103','8456', '8457')
--33992954 se duplico este registro con ts_correcion = 'S' en la tabla cc_tran_servicio - at_his_log_autoriza

--pag_t_concilia_broadnet
co_fec_cble                 co_autoriz_bco co_num_ref co_num_bin  co_valor                   co_fecha_trx                co_hora_trn co_hora_trn_local co_resultado  co_estatus_bco co_estatus_emp_serv co_conciliada co_usuario co_canal co_nombre                                co_celular      co_tip_trx  co_nro_cuenta co_tipo_cuenta co_fecha_archivo            co_fecha_real               co_forma_pago co_debito                  co_empresa co_num_autoriz 
--------------------------- -------------- ---------- ----------- -------------------------- --------------------------- ----------- ----------------- ------------- -------------- ------------------- ------------- ---------- -------- ---------------------------------------- --------------- ----------- ------------- -------------- --------------------------- --------------------------- ------------- -------------------------- ---------- -------------- 
Apr 11 2022 12:00AM         496646         113319     827623      5.00                       Apr 11 2022 12:00AM         102434      000000            IE            NO             SI                  (null)        (null)     (null)   (null)                                   (null)          (null)      (null)        (null)         Apr 12 2022 12:00AM         (null)                      (null)        (null)                     103        496646         

--cc_tran_servicio -33992954 DUPLICATE
ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
33992953      0              4014                F        Apr 11 2022 12:00AM         0        ope998                                                           consola                                                          5      N             33992953    (null)     L         BOLIVSRV                       0996192002      0             0             0           0031006699               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           103      (null)      0.00                       (null)                      5.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          (null)         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         CONSUMIDOR FINAL                                                                                                         (null)    Apr 11 2022  9:27AM         0              927388324   (null)           (null)        (null)          (null)   (null)            (null)                         9999999999                     0            
33992954      0              4014                F        Apr 11 2022 12:00AM         0        ope998                                                           consola                                                          5      S             33992953    (null)     L         BOLIVSRV                       0996192002      0             0             0           0031006699               1         0          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           N           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           103      (null)      0.00                       (null)                      5.00                       (null)                      0             0          (null)                                                           0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          (null)         0           0                 0           (null)                   0               0.00                       0.00                       0.00                       0        (null)               (null)             (null)       (null)                   A          (null)                      (null)                      (null)                      IBK              (null)       (null)      (null)               0.00                       0.00                       0.00                       (null)                         CONSUMIDOR FINAL                                                                                                         (null)    Apr 11 2022  9:27AM         0              927388324   (null)           (null)        (null)          (null)   (null)            (null)                         9999999999                     0            

--cob_atm..at_his_log_autoriza hl_reverso = 'S' hl_recib
cob_atem
hl_fecha_hora               hl_fecha_real               hl_fecha hl_hora hl_empresa hl_ced_ruc    hl_tarjeta           hl_terminal hl_banco    hl_ttrn     hl_trn      hl_sec_host hl_recibo   hl_tipocta1 hl_cuenta1               hl_tipocta2 hl_cuenta2               hl_reverso hl_moneda hl_monto                   hl_autorizacion hl_num_lote hl_referencia                            hl_local                  hl_ciudad    hl_dispositivo hl_estado hl_fecha_act                hl_tsfecha                  hl_signo hl_codigo_local hl_giro_de_comercio hl_procesado hl_codtarjeta hl_codcliente hl_offline hl_reentry 
--------------------------- --------------------------- -------- ------- ---------- ------------- -------------------- ----------- ----------- ----------- ----------- ----------- ----------- ----------- ------------------------ ----------- ------------------------ ---------- --------- -------------------------- --------------- ----------- ---------------------------------------- ------------------------- ------------ -------------- --------- --------------------------- --------------------------- -------- --------------- ------------------- ------------ ------------- ------------- ---------- ---------- 
Apr 11 2022 12:00AM         Apr 11 2022  9:26AM         20220411 092632  1342       9999999999    ' '   000000         ope998      37          0           4014        33992954    33992953    AHO         0031006699               (null)      (null)                   S          1         5.00                       113319          (null)      0984655616                               (null)                    (null)       3              I         Apr 11 2022 12:00AM         Apr 11 2022 12:00AM         D        (null)          (null)              (null)       (null)        (null)        N          N          

--cc_l_auxiliar_recarga
ar_celular ar_operadora ar_secuencial            ai_efectivo                ai_debito                  ar_fec_proceso              ar_canal ar_hora                     ar_nombre                      ar_tipo_trx ar_usuario      ar_oficina  ar_ubicacion ai_forma_pago ai_tipo_cuenta ai_cuenta            ai_resultado    ai_error             ai_fecha_concilia 
---------- ------------ ------------------------ -------------------------- -------------------------- --------------------------- -------- --------------------------- ------------------------------ ----------- --------------- ----------- ------------ ------------- -------------- -------------------- --------------- -------------------- ----------------- 
0984655616 103          33992953.0               0.00                       5.00                       Apr 11 2022 12:00AM         IBK      Apr 11 2022  9:26AM         CONSUMIDOR FINAL               4014        ope998          0           0            DEB           AHO            0031006699           (null)          (null)               (null)            


--------------------------------------ELIMINAR-----------------------------------------------------------------------------------
--delete FROM pag_t_concilia_broadnet where co_empresa in('103','8456', '8457')

exec pa_pag_c_concilia_broadnet_s
    @e_fecha = '4/11/2022',
    @e_empresa = '103',
    @e_siguiente = 0,
    @e_estado_bco = 'NO',
    @e_estado_emp = 'SI',
    @e_forma_pago = null


----------------------------------PRUEBAS PARA MOVISTAR VENTANILLA--------------------------
--delete from pag_t_concilia_broadnet where co_empresa in('103')
--delete from cob_cuentas..cc_tran_servicio where ts_fecha = '04/11/2022' and ts_causa = '103'
--delete from cob_atm..at_his_log_autoriza where hl_tsfecha =  '04/11/2022' 

--solo cambiar ts_secuencial  | ts_correccion a S
select * from cob_cuentas..cc_tran_servicio where ts_secuencial = 770200425
ts_secuencial ts_cod_alterno ts_tipo_transaccion ts_clase ts_tsfecha                  ts_tabla ts_usuario                                                       ts_terminal                                                      ts_rol ts_correccion ts_ssn_corr ts_reentry ts_origen ts_nodo                        ts_referencia   ts_remoto_ssn ts_cheque_rec ts_ctacte   ts_cta_banco             ts_filial ts_oficina ts_oficial ts_fecha_aper               ts_cliente  ts_ced_ruc    ts_estado ts_direccion_ec ts_descripcion_ec                                                                                                        ts_ciclo ts_categoria ts_producto ts_tipo ts_indicador ts_moneda ts_default  ts_tipo_def ts_rol_ente ts_tipo_promedio ts_numero ts_fecha                    ts_autorizante                                                   ts_causa ts_servicio ts_saldo                   ts_fecha_uso                ts_monto                   ts_fecha_ven                ts_filial_aut ts_ofi_aut ts_autoriz_aut                                                   ts_filial_anula ts_ofi_anula ts_autoriz_anula                                                 ts_cheque_desde ts_cheque_hasta ts_chequera ts_num_cheques ts_departamento ts_cta_gir               ts_endoso   ts_cod_banco ts_corresponsal ts_propietario ts_carta    ts_sec_correccion ts_cheque   ts_cta_banco_dep         ts_oficina_pago ts_contratado              ts_valor                   ts_ocasional               ts_banco ts_ccontable         ts_cta_funcionario ts_mercantil ts_cta_asociada          ts_tipocta ts_fecha_eimp               ts_fecha_rimp               ts_fecha_rofi               ts_tipo_chequera ts_stick_imp ts_tipo_imp ts_tarjcred          ts_aporte_iess             ts_descuento_iess          ts_fonres_iess             ts_agente                      ts_nombre                                                                                                                ts_debito ts_hora                     ts_oficina_cta ts_tsn      ts_tipo_contable ts_estado_sob ts_tipo_credito ts_plazo ts_tipo_sobregiro ts_campo_alt_uno               ts_campo_alt_dos               ts_ubicacion 
------------- -------------- ------------------- -------- --------------------------- -------- ---------------------------------------------------------------- ---------------------------------------------------------------- ------ ------------- ----------- ---------- --------- ------------------------------ --------------- ------------- ------------- ----------- ------------------------ --------- ---------- ---------- --------------------------- ----------- ------------- --------- --------------- ------------------------------------------------------------------------------------------------------------------------ -------- ------------ ----------- ------- ------------ --------- ----------- ----------- ----------- ---------------- --------- --------------------------- ---------------------------------------------------------------- -------- ----------- -------------------------- --------------------------- -------------------------- --------------------------- ------------- ---------- ---------------------------------------------------------------- --------------- ------------ ---------------------------------------------------------------- --------------- --------------- ----------- -------------- --------------- ------------------------ ----------- ------------ --------------- -------------- ----------- ----------------- ----------- ------------------------ --------------- -------------------------- -------------------------- -------------------------- -------- -------------------- ------------------ ------------ ------------------------ ---------- --------------------------- --------------------------- --------------------------- ---------------- ------------ ----------- -------------------- -------------------------- -------------------------- -------------------------- ------------------------------ ------------------------------------------------------------------------------------------------------------------------ --------- --------------------------- -------------- ----------- ---------------- ------------- --------------- -------- ----------------- ------------------------------ ------------------------------ ------------ 
770200425     0              4014                F        Apr 11 2022 12:00AM         0        apareder                                                         PMASUP100                                                        244    N             770200425   (null)     L         BOLIVSRV                       0979396983      0             0             0           (null)                   1         1          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           S           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           103      (null)      0.00                       (null)                      0.00                       (null)                      0             0          0.89                                                             0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          522865         0           0                 0           (null)                   0               0.00                       1.00                       0.00                       0        (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       0.00                       0.00                       0.11                           CONSUMIDOR FINAL                                                                                                         (null)    Apr 11 2022 11:52AM         0              588         (null)           (null)        (null)          (null)   (null)            001-024-0345795                9999999999                     108          
770200426     0              4014                F        Apr 11 2022 12:00AM         0        apareder                                                         PMASUP100                                                        244    S             770200425   (null)     L         BOLIVSRV                       0979396983      0             0             0           (null)                   1         1          0          (null)                      0           (null)        (null)    0               (null)                                                                                                                   (null)   (null)       0           L       0            1         0           S           (null)      (null)           0         Apr 11 2022 12:00AM         (null)                                                           103      (null)      0.00                       (null)                      0.00                       (null)                      0             0          0.89                                                             0               0            (null)                                                           0               0               0           0              0               (null)                   0           (null)       (null)          522865         0           0                 0           (null)                   0               0.00                       1.00                       0.00                       0        (null)               (null)             (null)       (null)                   C          (null)                      (null)                      (null)                      VEN              (null)       (null)      (null)               0.00                       0.00                       0.00                       0.11                           CONSUMIDOR FINAL                                                                                                         (null)    Apr 11 2022 11:52AM         0              588         (null)           (null)        (null)          (null)   (null)            001-024-0345795                9999999999                     108          

--solo cambiar hl_sec_host | hl_reverso a S
select * from cob_atm..at_his_log_autoriza where hl_sec_host = 770200425 
hl_fecha_hora               hl_fecha_real               hl_fecha hl_hora hl_empresa hl_ced_ruc    hl_tarjeta           hl_terminal hl_banco    hl_ttrn     hl_trn      hl_sec_host hl_recibo   hl_tipocta1 hl_cuenta1               hl_tipocta2 hl_cuenta2               hl_reverso hl_moneda hl_monto                   hl_autorizacion hl_num_lote hl_referencia                            hl_local                  hl_ciudad    hl_dispositivo hl_estado hl_fecha_act                hl_tsfecha                  hl_signo hl_codigo_local hl_giro_de_comercio hl_procesado hl_codtarjeta hl_codcliente hl_offline hl_reentry 
--------------------------- --------------------------- -------- ------- ---------- ------------- -------------------- ----------- ----------- ----------- ----------- ----------- ----------- ----------- ------------------------ ----------- ------------------------ ---------- --------- -------------------------- --------------- ----------- ---------------------------------------- ------------------------- ------------ -------------- --------- --------------------------- --------------------------- -------- --------------- ------------------- ------------ ------------- ------------- ---------- ---------- 
Apr 11 2022 12:00AM         Apr 11 2022 11:52AM         20220411 115211  1342       9999999999    ' '   000000         apareder    37          0           4014        770200425   770200425   EFE         (null)                   (null)      (null)                   N          1         1.00                       117116          (null)      0979396983                               (null)                    (null)       8              I         Apr 11 2022 12:00AM         Apr 11 2022 12:00AM         D        (null)          (null)              (null)       (null)        (null)        N          N          
Apr 11 2022 12:00AM         Apr 11 2022 11:52AM         20220411 115211  1342       9999999999    ' '   000000         apareder    37          0           4014        770200426   770200425   EFE         (null)                   (null)      (null)                   S          1         1.00                       117116          (null)      0979396983                               (null)                    (null)       8              I         Apr 11 2022 12:00AM         Apr 11 2022 12:00AM         D        (null)          (null)              (null)       (null)        (null)        N          N          



select * from pag_t_concilia_broadnet where co_empresa in('103')
co_fec_cble                 co_autoriz_bco co_num_ref co_num_bin  co_valor                   co_fecha_trx                co_hora_trn co_hora_trn_local co_resultado  co_estatus_bco co_estatus_emp_serv co_conciliada co_usuario co_canal co_nombre                                co_celular      co_tip_trx  co_nro_cuenta co_tipo_cuenta co_fecha_archivo            co_fecha_real               co_forma_pago co_debito                  co_empresa co_num_autoriz 
--------------------------- -------------- ---------- ----------- -------------------------- --------------------------- ----------- ----------------- ------------- -------------- ------------------- ------------- ---------- -------- ---------------------------------------- --------------- ----------- ------------- -------------- --------------------------- --------------------------- ------------- -------------------------- ---------- -------------- 
Apr 11 2022 12:00AM         770200425      117116     827623      1.00                       Apr 11 2022 12:00AM         115214      115200            OK            SI             SI                  (null)        apareder   VEN      CONSUMIDOR FINAL                         0979396983      4014        (null)        C              Apr 12 2022 12:00AM         Apr 25 2022 12:09PM         (null)        0.00                       103        522865         

select * from cob_pagos..cc_l_auxiliar_recarga where ar_secuencial = 770200425
ar_celular ar_operadora ar_secuencial            ai_efectivo                ai_debito                  ar_fec_proceso              ar_canal ar_hora                     ar_nombre                      ar_tipo_trx ar_usuario      ar_oficina  ar_ubicacion ai_forma_pago ai_tipo_cuenta ai_cuenta            ai_resultado    ai_error             ai_fecha_concilia 
---------- ------------ ------------------------ -------------------------- -------------------------- --------------------------- -------- --------------------------- ------------------------------ ----------- --------------- ----------- ------------ ------------- -------------- -------------------- --------------- -------------------- ----------------- 
0979396983 103          770200425.0              1.00                       0.00                       Apr 11 2022 12:00AM         VEN      Apr 11 2022 11:52AM         CONSUMIDOR FINAL               4014        apareder        1           0            EFE           CTE            (null)               (null)          (null)               (null)            


exec pa_pag_c_concilia_broadnet_s
@e_fecha = '4/11/2022',
@e_empresa = '103',
@e_siguiente = 0,
@e_estado_bco = 'NO',
@e_estado_emp = 'SI',
@e_forma_pago = null