<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../../../Tareas%20Elizabeth/SAT-2018/CASH%20-%20CyberBank/06-Pagos%20de%20Servicios/ServiciosRecaudaciones/DOCUMENTACIONMAPEO/Project4/xsd/SRI_1.wsdl"/>
      <rootElement name="MensajeSalidaReversarOtrasFormasPago" namespace="http://www.bolivariano.com/MensajeSRI"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../../../Tareas%20Elizabeth/SAT-2018/CASH%20-%20CyberBank/06-Pagos%20de%20Servicios/ServiciosRecaudaciones/DOCUMENTACIONMAPEO/Project4/otc-nopolicy.wsdl"/>
      <rootElement name="salidaEjecutarPago" namespace="http://www.bolivariano.com/ws/OTCService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE MAY 22 09:13:32 COT 2018]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://www.bolivariano.com/FormaPago"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns2="http://www.bolivariano.com/Vehiculo"
                xmlns:ns3="http://www.bolivariano.com/Enumerados"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xsd1="http://www.bolivariano.com/MensajeSRI"
                xmlns:ns11="http://www.bolivariano.com/dominio/DatoAdicional"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns5="http://www.bolivariano.com/CoreBB"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://www.bolivariano.com/Cuenta"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ns17="http://www.bolivariano.com/dominio/Convenio"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://www.bolivariano.com/ws/SRI/"
                xmlns:ns18="http://www.bolivariano.com/dominio/Recibo"
                xmlns:ns21="http://www.bolivariano.com/dominio/RegionalArea"
                xmlns:ns22="http://www.bolivariano.com/dominio/ListaSeleccion"
                xmlns:ns13="http://www.bolivariano.com/dominio/Servicio"
                xmlns:ns1="http://www.bolivariano.com/MensajeBolivariano"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns4="http://www.bolivariano.com/Recaudo"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns14="http://www.bolivariano.com/dominio/TipoMatriculacion"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns15="http://www.bolivariano.com/dominio/FormaPago"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns16="http://www.bolivariano.com/dominio/TipoIdentificador"
                xmlns:ns12="http://www.bolivariano.com/ws/OTCService"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns7="http://www.bolivariano.com/Producto"
                xmlns:ns8="http://www.bolivariano.com/Cliente"
                xmlns:ns19="http://www.bolivariano.com/dominio/Empresa"
                xmlns:ns9="http://www.bolivariano.com/Comision"
                xmlns:ns20="http://www.bolivariano.com/mensaje/MensajeOTC"
                xmlns:ns10="http://www.bolivariano.com/SRI"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:java="java"
                exclude-result-prefixes="xsi xsl ns0 ns2 ns3 xsd1 soap ns5 wsdl ns6 tns ns1 ns4 xsd ns7 ns8 ns9 ns10 ns11 ns17 ns18 ns21 ns22 ns13 ns14 ns15 ns16 ns12 ns19 ns20 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
  <xsl:choose>
      <xsl:when test="/xsd1:MensajeSalidaReversarOtrasFormasPago/codigoError='0'">
    <ns20:salidaEjecutarPago>  
      <ns20:fechaDebito>
        <xsl:value-of select='java:format(java:text.SimpleDateFormat.new("yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSS"), java:util.Date.new())'/>
    </ns20:fechaDebito>
      <ns20:fechaPago>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/fechaContable"/>
      </ns20:fechaPago>  
      <ns20:datosAdicionales>
         <xsl:call-template name="datosAdicionales"/>       
      </ns20:datosAdicionales> 
        <ns20:referencia>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/mcn"/>
      </ns20:referencia>
        <ns20:codigoError>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/codigoError"/>
      </ns20:codigoError>
       <ns20:nombreCliente>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/nombre"/>
      </ns20:nombreCliente>
       <ns20:mensajeUsuario>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/mensajeUsuario"/>
      </ns20:mensajeUsuario>
    </ns20:salidaEjecutarPago>
     </xsl:when>
     <xsl:otherwise>
     <ns20:salidaEjecutarPago>
      <ns20:codigoError>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/codigoError"/>
      </ns20:codigoError>      
      <ns20:mensajeUsuario>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/mensajeUsuario"/>
      </ns20:mensajeUsuario>      
    </ns20:salidaEjecutarPago>     
       </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
   <xsl:template name="datosAdicionales">
    <ns20:datoAdicional>
      <codigo>01</codigo>
      <!-- llenar desde el componente-->
      <etiqueta>No. autorizacion SRI:</etiqueta>
      <!-- llenar desde el componente-->
      <valor>
        <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/autorizacionSRI"/>
      </valor>
      <visible>true</visible>
      <!-- llenar desde el componente-->
    </ns20:datoAdicional>
    <ns20:datoAdicional>
          <codigo>02</codigo>
          <etiqueta>fechaVenSRI</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/fechaVenSRI"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
         <ns20:datoAdicional>
          <codigo>03</codigo>
          <etiqueta>logSRI</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/logSRI"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
         <ns20:datoAdicional>
          <codigo>04</codigo>
          <etiqueta>mcn</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/mcn"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
        <ns20:datoAdicional>
          <codigo>05</codigo>
          <etiqueta>impuesto</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/impuesto"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
        <ns20:datoAdicional>
          <codigo>06</codigo>
          <etiqueta>interes</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/interes"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
        <ns20:datoAdicional>
          <codigo>07</codigo>
          <etiqueta>multa</etiqueta>
          <valor>
            <xsl:value-of select="/xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/multa"/>
          </valor>
          <visible>false</visible>
        </ns20:datoAdicional>
        <!--KBastida Ini-->
        <ns20:datoAdicional>
          <codigo>08</codigo>
          <etiqueta>Código IFI de Transacción</etiqueta>
          <valor>
            <xsl:value-of select='concat(java:format(java:text.SimpleDateFormat.new("yyyyMMdd"), java:util.Date.new()), /xsd1:MensajeSalidaReversarOtrasFormasPago/informacionSRI/mcn)'/>
          </valor>
          <visible>true</visible>
        </ns20:datoAdicional>
       
        <!--Fin-->
  </xsl:template>
</xsl:stylesheet>
